/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ScriptMenusPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/settings.ts
var import_obsidian2 = require("obsidian");

// src/modal.ts
var import_obsidian = require("obsidian");

// src/generated/icon-list.ts
var ICON_LIST = [
  "a-arrow-down",
  "a-arrow-up",
  "a-large-small",
  "accessibility",
  "activity",
  "activity-square",
  "air-vent",
  "airplay",
  "alarm-clock",
  "alarm-clock-check",
  "alarm-clock-minus",
  "alarm-clock-off",
  "alarm-clock-plus",
  "alarm-smoke",
  "album",
  "alert-circle",
  "alert-octagon",
  "alert-triangle",
  "align-center",
  "align-center-horizontal",
  "align-center-vertical",
  "align-end-horizontal",
  "align-end-vertical",
  "align-horizontal-distribute-center",
  "align-horizontal-distribute-end",
  "align-horizontal-distribute-start",
  "align-horizontal-justify-center",
  "align-horizontal-justify-end",
  "align-horizontal-justify-start",
  "align-horizontal-space-around",
  "align-horizontal-space-between",
  "align-justify",
  "align-left",
  "align-right",
  "align-start-horizontal",
  "align-start-vertical",
  "align-vertical-distribute-center",
  "align-vertical-distribute-end",
  "align-vertical-distribute-start",
  "align-vertical-justify-center",
  "align-vertical-justify-end",
  "align-vertical-justify-start",
  "align-vertical-space-around",
  "align-vertical-space-between",
  "ambulance",
  "ampersand",
  "ampersands",
  "anchor",
  "angry",
  "annoyed",
  "antenna",
  "anvil",
  "aperture",
  "app-window",
  "apple",
  "archive",
  "archive-restore",
  "archive-x",
  "area-chart",
  "armchair",
  "arrow-big-down",
  "arrow-big-down-dash",
  "arrow-big-left",
  "arrow-big-left-dash",
  "arrow-big-right",
  "arrow-big-right-dash",
  "arrow-big-up",
  "arrow-big-up-dash",
  "arrow-down",
  "arrow-down-0-1",
  "arrow-down-1-0",
  "arrow-down-a-z",
  "arrow-down-circle",
  "arrow-down-from-line",
  "arrow-down-left",
  "arrow-down-left-from-circle",
  "arrow-down-left-from-square",
  "arrow-down-left-square",
  "arrow-down-narrow-wide",
  "arrow-down-right",
  "arrow-down-right-from-circle",
  "arrow-down-right-from-square",
  "arrow-down-right-square",
  "arrow-down-square",
  "arrow-down-to-dot",
  "arrow-down-to-line",
  "arrow-down-up",
  "arrow-down-wide-narrow",
  "arrow-down-z-a",
  "arrow-left",
  "arrow-left-circle",
  "arrow-left-from-line",
  "arrow-left-right",
  "arrow-left-square",
  "arrow-left-to-line",
  "arrow-right",
  "arrow-right-circle",
  "arrow-right-from-line",
  "arrow-right-left",
  "arrow-right-square",
  "arrow-right-to-line",
  "arrow-up",
  "arrow-up-0-1",
  "arrow-up-1-0",
  "arrow-up-a-z",
  "arrow-up-circle",
  "arrow-up-down",
  "arrow-up-from-dot",
  "arrow-up-from-line",
  "arrow-up-left",
  "arrow-up-left-from-circle",
  "arrow-up-left-from-square",
  "arrow-up-left-square",
  "arrow-up-narrow-wide",
  "arrow-up-right",
  "arrow-up-right-from-circle",
  "arrow-up-right-from-square",
  "arrow-up-right-square",
  "arrow-up-square",
  "arrow-up-to-line",
  "arrow-up-wide-narrow",
  "arrow-up-z-a",
  "arrows-up-from-line",
  "asterisk",
  "asterisk-square",
  "at-sign",
  "atom",
  "audio-lines",
  "audio-waveform",
  "award",
  "axe",
  "axis-3d",
  "baby",
  "backpack",
  "badge",
  "badge-alert",
  "badge-cent",
  "badge-check",
  "badge-dollar-sign",
  "badge-euro",
  "badge-help",
  "badge-indian-rupee",
  "badge-info",
  "badge-japanese-yen",
  "badge-minus",
  "badge-percent",
  "badge-plus",
  "badge-pound-sterling",
  "badge-russian-ruble",
  "badge-swiss-franc",
  "badge-x",
  "baggage-claim",
  "ban",
  "banana",
  "banknote",
  "bar-chart",
  "bar-chart-2",
  "bar-chart-3",
  "bar-chart-4",
  "bar-chart-big",
  "bar-chart-horizontal",
  "bar-chart-horizontal-big",
  "barcode",
  "baseline",
  "bath",
  "battery",
  "battery-charging",
  "battery-full",
  "battery-low",
  "battery-medium",
  "battery-warning",
  "beaker",
  "bean",
  "bean-off",
  "bed",
  "bed-double",
  "bed-single",
  "beef",
  "beer",
  "bell",
  "bell-dot",
  "bell-electric",
  "bell-minus",
  "bell-off",
  "bell-plus",
  "bell-ring",
  "between-horizontal-end",
  "between-horizontal-start",
  "between-vertical-end",
  "between-vertical-start",
  "bike",
  "binary",
  "biohazard",
  "bird",
  "bitcoin",
  "blend",
  "blinds",
  "blocks",
  "bluetooth",
  "bluetooth-connected",
  "bluetooth-off",
  "bluetooth-searching",
  "bold",
  "bolt",
  "bomb",
  "bone",
  "book",
  "book-a",
  "book-audio",
  "book-check",
  "book-copy",
  "book-dashed",
  "book-down",
  "book-headphones",
  "book-heart",
  "book-image",
  "book-key",
  "book-lock",
  "book-marked",
  "book-minus",
  "book-open",
  "book-open-check",
  "book-open-text",
  "book-plus",
  "book-text",
  "book-type",
  "book-up",
  "book-up-2",
  "book-user",
  "book-x",
  "bookmark",
  "bookmark-check",
  "bookmark-minus",
  "bookmark-plus",
  "bookmark-x",
  "boom-box",
  "bot",
  "bot-message-square",
  "box",
  "box-select",
  "boxes",
  "braces",
  "brackets",
  "brain",
  "brain-circuit",
  "brain-cog",
  "brick-wall",
  "briefcase",
  "bring-to-front",
  "brush",
  "bug",
  "bug-off",
  "bug-play",
  "building",
  "building-2",
  "bus",
  "bus-front",
  "cable",
  "cable-car",
  "cake",
  "cake-slice",
  "calculator",
  "calendar",
  "calendar-check",
  "calendar-check-2",
  "calendar-clock",
  "calendar-days",
  "calendar-fold",
  "calendar-heart",
  "calendar-minus",
  "calendar-minus-2",
  "calendar-off",
  "calendar-plus",
  "calendar-plus-2",
  "calendar-range",
  "calendar-search",
  "calendar-x",
  "calendar-x-2",
  "camera",
  "camera-off",
  "candlestick-chart",
  "candy",
  "candy-cane",
  "candy-off",
  "captions",
  "captions-off",
  "car",
  "car-front",
  "car-taxi-front",
  "caravan",
  "carrot",
  "case-lower",
  "case-sensitive",
  "case-upper",
  "cassette-tape",
  "cast",
  "castle",
  "cat",
  "cctv",
  "check",
  "check-check",
  "check-circle",
  "check-circle-2",
  "check-square",
  "check-square-2",
  "chef-hat",
  "cherry",
  "chevron-down",
  "chevron-down-circle",
  "chevron-down-square",
  "chevron-first",
  "chevron-last",
  "chevron-left",
  "chevron-left-circle",
  "chevron-left-square",
  "chevron-right",
  "chevron-right-circle",
  "chevron-right-square",
  "chevron-up",
  "chevron-up-circle",
  "chevron-up-square",
  "chevrons-down",
  "chevrons-down-up",
  "chevrons-left",
  "chevrons-left-right",
  "chevrons-right",
  "chevrons-right-left",
  "chevrons-up",
  "chevrons-up-down",
  "chrome",
  "church",
  "cigarette",
  "cigarette-off",
  "circle",
  "circle-dashed",
  "circle-dollar-sign",
  "circle-dot",
  "circle-dot-dashed",
  "circle-ellipsis",
  "circle-equal",
  "circle-fading-plus",
  "circle-off",
  "circle-slash",
  "circle-slash-2",
  "circle-user",
  "circle-user-round",
  "circuit-board",
  "citrus",
  "clapperboard",
  "clipboard",
  "clipboard-check",
  "clipboard-copy",
  "clipboard-list",
  "clipboard-minus",
  "clipboard-paste",
  "clipboard-pen",
  "clipboard-pen-line",
  "clipboard-plus",
  "clipboard-type",
  "clipboard-x",
  "clock",
  "clock-1",
  "clock-10",
  "clock-11",
  "clock-12",
  "clock-2",
  "clock-3",
  "clock-4",
  "clock-5",
  "clock-6",
  "clock-7",
  "clock-8",
  "clock-9",
  "cloud",
  "cloud-cog",
  "cloud-drizzle",
  "cloud-fog",
  "cloud-hail",
  "cloud-lightning",
  "cloud-moon",
  "cloud-moon-rain",
  "cloud-off",
  "cloud-rain",
  "cloud-rain-wind",
  "cloud-snow",
  "cloud-sun",
  "cloud-sun-rain",
  "cloudy",
  "clover",
  "club",
  "code",
  "code-2",
  "code-square",
  "codepen",
  "codesandbox",
  "coffee",
  "cog",
  "coins",
  "columns-2",
  "columns-3",
  "columns-4",
  "combine",
  "command",
  "compass",
  "component",
  "computer",
  "concierge-bell",
  "cone",
  "construction",
  "contact",
  "contact-2",
  "container",
  "contrast",
  "cookie",
  "cooking-pot",
  "copy",
  "copy-check",
  "copy-minus",
  "copy-plus",
  "copy-slash",
  "copy-x",
  "copyleft",
  "copyright",
  "corner-down-left",
  "corner-down-right",
  "corner-left-down",
  "corner-left-up",
  "corner-right-down",
  "corner-right-up",
  "corner-up-left",
  "corner-up-right",
  "cpu",
  "creative-commons",
  "credit-card",
  "croissant",
  "crop",
  "cross",
  "crosshair",
  "crown",
  "cuboid",
  "cup-soda",
  "currency",
  "cylinder",
  "database",
  "database-backup",
  "database-zap",
  "delete",
  "dessert",
  "diameter",
  "diamond",
  "dice-1",
  "dice-2",
  "dice-3",
  "dice-4",
  "dice-5",
  "dice-6",
  "dices",
  "diff",
  "disc",
  "disc-2",
  "disc-3",
  "disc-album",
  "divide",
  "divide-circle",
  "divide-square",
  "dna",
  "dna-off",
  "dog",
  "dollar-sign",
  "donut",
  "door-closed",
  "door-open",
  "dot",
  "dot-square",
  "download",
  "download-cloud",
  "drafting-compass",
  "drama",
  "dribbble",
  "drill",
  "droplet",
  "droplets",
  "drum",
  "drumstick",
  "dumbbell",
  "ear",
  "ear-off",
  "earth",
  "earth-lock",
  "eclipse",
  "egg",
  "egg-fried",
  "egg-off",
  "equal",
  "equal-not",
  "equal-square",
  "eraser",
  "euro",
  "expand",
  "external-link",
  "eye",
  "eye-off",
  "facebook",
  "factory",
  "fan",
  "fast-forward",
  "feather",
  "fence",
  "ferris-wheel",
  "figma",
  "file",
  "file-archive",
  "file-audio",
  "file-audio-2",
  "file-axis-3d",
  "file-badge",
  "file-badge-2",
  "file-bar-chart",
  "file-bar-chart-2",
  "file-box",
  "file-check",
  "file-check-2",
  "file-clock",
  "file-code",
  "file-code-2",
  "file-cog",
  "file-diff",
  "file-digit",
  "file-down",
  "file-heart",
  "file-image",
  "file-input",
  "file-json",
  "file-json-2",
  "file-key",
  "file-key-2",
  "file-line-chart",
  "file-lock",
  "file-lock-2",
  "file-minus",
  "file-minus-2",
  "file-music",
  "file-output",
  "file-pen",
  "file-pen-line",
  "file-pie-chart",
  "file-plus",
  "file-plus-2",
  "file-question",
  "file-scan",
  "file-search",
  "file-search-2",
  "file-sliders",
  "file-spreadsheet",
  "file-stack",
  "file-symlink",
  "file-terminal",
  "file-text",
  "file-type",
  "file-type-2",
  "file-up",
  "file-video",
  "file-video-2",
  "file-volume",
  "file-volume-2",
  "file-warning",
  "file-x",
  "file-x-2",
  "files",
  "film",
  "filter",
  "filter-x",
  "fingerprint",
  "fire-extinguisher",
  "fish",
  "fish-off",
  "fish-symbol",
  "flag",
  "flag-off",
  "flag-triangle-left",
  "flag-triangle-right",
  "flame",
  "flame-kindling",
  "flashlight",
  "flashlight-off",
  "flask-conical",
  "flask-conical-off",
  "flask-round",
  "flip-horizontal",
  "flip-horizontal-2",
  "flip-vertical",
  "flip-vertical-2",
  "flower",
  "flower-2",
  "focus",
  "fold-horizontal",
  "fold-vertical",
  "folder",
  "folder-archive",
  "folder-check",
  "folder-clock",
  "folder-closed",
  "folder-cog",
  "folder-dot",
  "folder-down",
  "folder-git",
  "folder-git-2",
  "folder-heart",
  "folder-input",
  "folder-kanban",
  "folder-key",
  "folder-lock",
  "folder-minus",
  "folder-open",
  "folder-open-dot",
  "folder-output",
  "folder-pen",
  "folder-plus",
  "folder-root",
  "folder-search",
  "folder-search-2",
  "folder-symlink",
  "folder-sync",
  "folder-tree",
  "folder-up",
  "folder-x",
  "folders",
  "footprints",
  "forklift",
  "form-input",
  "forward",
  "frame",
  "framer",
  "frown",
  "fuel",
  "fullscreen",
  "function-square",
  "gallery-horizontal",
  "gallery-horizontal-end",
  "gallery-thumbnails",
  "gallery-vertical",
  "gallery-vertical-end",
  "gamepad",
  "gamepad-2",
  "gantt-chart",
  "gantt-chart-square",
  "gauge",
  "gauge-circle",
  "gavel",
  "gem",
  "ghost",
  "gift",
  "git-branch",
  "git-branch-plus",
  "git-commit-horizontal",
  "git-commit-vertical",
  "git-compare",
  "git-compare-arrows",
  "git-fork",
  "git-graph",
  "git-merge",
  "git-pull-request",
  "git-pull-request-arrow",
  "git-pull-request-closed",
  "git-pull-request-create",
  "git-pull-request-create-arrow",
  "git-pull-request-draft",
  "github",
  "gitlab",
  "glass-water",
  "glasses",
  "globe",
  "globe-lock",
  "goal",
  "grab",
  "graduation-cap",
  "grape",
  "grid-2x2",
  "grid-3x3",
  "grip",
  "grip-horizontal",
  "grip-vertical",
  "group",
  "guitar",
  "hammer",
  "hand",
  "hand-coins",
  "hand-heart",
  "hand-helping",
  "hand-metal",
  "hand-platter",
  "handshake",
  "hard-drive",
  "hard-drive-download",
  "hard-drive-upload",
  "hard-hat",
  "hash",
  "haze",
  "hdmi-port",
  "heading",
  "heading-1",
  "heading-2",
  "heading-3",
  "heading-4",
  "heading-5",
  "heading-6",
  "headphones",
  "headset",
  "heart",
  "heart-crack",
  "heart-handshake",
  "heart-off",
  "heart-pulse",
  "heater",
  "help-circle",
  "hexagon",
  "highlighter",
  "history",
  "home",
  "hop",
  "hop-off",
  "hotel",
  "hourglass",
  "ice-cream",
  "ice-cream-2",
  "image",
  "image-down",
  "image-minus",
  "image-off",
  "image-plus",
  "image-up",
  "images",
  "import",
  "inbox",
  "indent",
  "indian-rupee",
  "infinity",
  "info",
  "inspection-panel",
  "instagram",
  "italic",
  "iteration-ccw",
  "iteration-cw",
  "japanese-yen",
  "joystick",
  "kanban",
  "kanban-square",
  "kanban-square-dashed",
  "key",
  "key-round",
  "key-square",
  "keyboard",
  "keyboard-music",
  "lamp",
  "lamp-ceiling",
  "lamp-desk",
  "lamp-floor",
  "lamp-wall-down",
  "lamp-wall-up",
  "land-plot",
  "landmark",
  "languages",
  "laptop",
  "laptop-2",
  "lasso",
  "lasso-select",
  "laugh",
  "layers",
  "layers-2",
  "layers-3",
  "layout-dashboard",
  "layout-grid",
  "layout-list",
  "layout-panel-left",
  "layout-panel-top",
  "layout-template",
  "leaf",
  "leafy-green",
  "library",
  "library-big",
  "library-square",
  "life-buoy",
  "ligature",
  "lightbulb",
  "lightbulb-off",
  "line-chart",
  "link",
  "link-2",
  "link-2-off",
  "linkedin",
  "list",
  "list-checks",
  "list-collapse",
  "list-end",
  "list-filter",
  "list-minus",
  "list-music",
  "list-ordered",
  "list-plus",
  "list-restart",
  "list-start",
  "list-todo",
  "list-tree",
  "list-video",
  "list-x",
  "loader",
  "loader-2",
  "locate",
  "locate-fixed",
  "locate-off",
  "lock",
  "lock-keyhole",
  "log-in",
  "log-out",
  "lollipop",
  "luggage",
  "m-square",
  "magnet",
  "mail",
  "mail-check",
  "mail-minus",
  "mail-open",
  "mail-plus",
  "mail-question",
  "mail-search",
  "mail-warning",
  "mail-x",
  "mailbox",
  "mails",
  "map",
  "map-pin",
  "map-pin-off",
  "map-pinned",
  "martini",
  "maximize",
  "maximize-2",
  "medal",
  "megaphone",
  "megaphone-off",
  "meh",
  "memory-stick",
  "menu",
  "menu-square",
  "merge",
  "message-circle",
  "message-circle-code",
  "message-circle-dashed",
  "message-circle-heart",
  "message-circle-more",
  "message-circle-off",
  "message-circle-plus",
  "message-circle-question",
  "message-circle-reply",
  "message-circle-warning",
  "message-circle-x",
  "message-square",
  "message-square-code",
  "message-square-dashed",
  "message-square-diff",
  "message-square-dot",
  "message-square-heart",
  "message-square-more",
  "message-square-off",
  "message-square-plus",
  "message-square-quote",
  "message-square-reply",
  "message-square-share",
  "message-square-text",
  "message-square-warning",
  "message-square-x",
  "messages-square",
  "mic",
  "mic-2",
  "mic-off",
  "microscope",
  "microwave",
  "milestone",
  "milk",
  "milk-off",
  "minimize",
  "minimize-2",
  "minus",
  "minus-circle",
  "minus-square",
  "monitor",
  "monitor-check",
  "monitor-dot",
  "monitor-down",
  "monitor-off",
  "monitor-pause",
  "monitor-play",
  "monitor-smartphone",
  "monitor-speaker",
  "monitor-stop",
  "monitor-up",
  "monitor-x",
  "moon",
  "moon-star",
  "more-horizontal",
  "more-vertical",
  "mountain",
  "mountain-snow",
  "mouse",
  "mouse-pointer",
  "mouse-pointer-2",
  "mouse-pointer-click",
  "mouse-pointer-square",
  "mouse-pointer-square-dashed",
  "move",
  "move-3d",
  "move-diagonal",
  "move-diagonal-2",
  "move-down",
  "move-down-left",
  "move-down-right",
  "move-horizontal",
  "move-left",
  "move-right",
  "move-up",
  "move-up-left",
  "move-up-right",
  "move-vertical",
  "music",
  "music-2",
  "music-3",
  "music-4",
  "navigation",
  "navigation-2",
  "navigation-2-off",
  "navigation-off",
  "network",
  "newspaper",
  "nfc",
  "notebook",
  "notebook-pen",
  "notebook-tabs",
  "notebook-text",
  "notepad-text",
  "notepad-text-dashed",
  "nut",
  "nut-off",
  "octagon",
  "option",
  "orbit",
  "outdent",
  "package",
  "package-2",
  "package-check",
  "package-minus",
  "package-open",
  "package-plus",
  "package-search",
  "package-x",
  "paint-bucket",
  "paint-roller",
  "paintbrush",
  "paintbrush-2",
  "palette",
  "palmtree",
  "panel-bottom",
  "panel-bottom-close",
  "panel-bottom-dashed",
  "panel-bottom-open",
  "panel-left",
  "panel-left-close",
  "panel-left-dashed",
  "panel-left-open",
  "panel-right",
  "panel-right-close",
  "panel-right-dashed",
  "panel-right-open",
  "panel-top",
  "panel-top-close",
  "panel-top-dashed",
  "panel-top-open",
  "panels-left-bottom",
  "panels-right-bottom",
  "panels-top-left",
  "paperclip",
  "parentheses",
  "parking-circle",
  "parking-circle-off",
  "parking-meter",
  "parking-square",
  "parking-square-off",
  "party-popper",
  "pause",
  "pause-circle",
  "pause-octagon",
  "paw-print",
  "pc-case",
  "pen",
  "pen-line",
  "pen-tool",
  "pencil",
  "pencil-line",
  "pencil-ruler",
  "pentagon",
  "percent",
  "percent-circle",
  "percent-diamond",
  "percent-square",
  "person-standing",
  "phone",
  "phone-call",
  "phone-forwarded",
  "phone-incoming",
  "phone-missed",
  "phone-off",
  "phone-outgoing",
  "pi",
  "pi-square",
  "piano",
  "pickaxe",
  "picture-in-picture",
  "picture-in-picture-2",
  "pie-chart",
  "piggy-bank",
  "pilcrow",
  "pilcrow-square",
  "pill",
  "pin",
  "pin-off",
  "pipette",
  "pizza",
  "plane",
  "plane-landing",
  "plane-takeoff",
  "play",
  "play-circle",
  "play-square",
  "plug",
  "plug-2",
  "plug-zap",
  "plug-zap-2",
  "plus",
  "plus-circle",
  "plus-square",
  "pocket",
  "pocket-knife",
  "podcast",
  "pointer",
  "pointer-off",
  "popcorn",
  "popsicle",
  "pound-sterling",
  "power",
  "power-circle",
  "power-off",
  "power-square",
  "presentation",
  "printer",
  "projector",
  "puzzle",
  "pyramid",
  "qr-code",
  "quote",
  "rabbit",
  "radar",
  "radiation",
  "radical",
  "radio",
  "radio-receiver",
  "radio-tower",
  "radius",
  "rail-symbol",
  "rainbow",
  "rat",
  "ratio",
  "receipt",
  "receipt-cent",
  "receipt-euro",
  "receipt-indian-rupee",
  "receipt-japanese-yen",
  "receipt-pound-sterling",
  "receipt-russian-ruble",
  "receipt-swiss-franc",
  "receipt-text",
  "rectangle-horizontal",
  "rectangle-vertical",
  "recycle",
  "redo",
  "redo-2",
  "redo-dot",
  "refresh-ccw",
  "refresh-ccw-dot",
  "refresh-cw",
  "refresh-cw-off",
  "refrigerator",
  "regex",
  "remove-formatting",
  "repeat",
  "repeat-1",
  "repeat-2",
  "replace",
  "replace-all",
  "reply",
  "reply-all",
  "rewind",
  "ribbon",
  "rocket",
  "rocking-chair",
  "roller-coaster",
  "rotate-3d",
  "rotate-ccw",
  "rotate-cw",
  "route",
  "route-off",
  "router",
  "rows-2",
  "rows-3",
  "rows-4",
  "rss",
  "ruler",
  "russian-ruble",
  "sailboat",
  "salad",
  "sandwich",
  "satellite",
  "satellite-dish",
  "save",
  "save-all",
  "scale",
  "scale-3d",
  "scaling",
  "scan",
  "scan-barcode",
  "scan-eye",
  "scan-face",
  "scan-line",
  "scan-search",
  "scan-text",
  "scatter-chart",
  "school",
  "school-2",
  "scissors",
  "scissors-line-dashed",
  "scissors-square",
  "scissors-square-dashed-bottom",
  "screen-share",
  "screen-share-off",
  "scroll",
  "scroll-text",
  "search",
  "search-check",
  "search-code",
  "search-slash",
  "search-x",
  "send",
  "send-horizontal",
  "send-to-back",
  "separator-horizontal",
  "separator-vertical",
  "server",
  "server-cog",
  "server-crash",
  "server-off",
  "settings",
  "settings-2",
  "shapes",
  "share",
  "share-2",
  "sheet",
  "shell",
  "shield",
  "shield-alert",
  "shield-ban",
  "shield-check",
  "shield-ellipsis",
  "shield-half",
  "shield-minus",
  "shield-off",
  "shield-plus",
  "shield-question",
  "shield-x",
  "ship",
  "ship-wheel",
  "shirt",
  "shopping-bag",
  "shopping-basket",
  "shopping-cart",
  "shovel",
  "shower-head",
  "shrink",
  "shrub",
  "shuffle",
  "sigma",
  "sigma-square",
  "signal",
  "signal-high",
  "signal-low",
  "signal-medium",
  "signal-zero",
  "signpost",
  "signpost-big",
  "siren",
  "skip-back",
  "skip-forward",
  "skull",
  "slack",
  "slash",
  "slash-square",
  "slice",
  "sliders",
  "sliders-horizontal",
  "smartphone",
  "smartphone-charging",
  "smartphone-nfc",
  "smile",
  "smile-plus",
  "snail",
  "snowflake",
  "sofa",
  "soup",
  "space",
  "spade",
  "sparkle",
  "sparkles",
  "speaker",
  "speech",
  "spell-check",
  "spell-check-2",
  "spline",
  "split",
  "split-square-horizontal",
  "split-square-vertical",
  "spray-can",
  "sprout",
  "square",
  "square-dashed-bottom",
  "square-dashed-bottom-code",
  "square-pen",
  "square-radical",
  "square-stack",
  "square-user",
  "square-user-round",
  "squircle",
  "squirrel",
  "stamp",
  "star",
  "star-half",
  "star-off",
  "step-back",
  "step-forward",
  "stethoscope",
  "sticker",
  "sticky-note",
  "stop-circle",
  "store",
  "stretch-horizontal",
  "stretch-vertical",
  "strikethrough",
  "subscript",
  "sun",
  "sun-dim",
  "sun-medium",
  "sun-moon",
  "sun-snow",
  "sunrise",
  "sunset",
  "superscript",
  "swatch-book",
  "swiss-franc",
  "switch-camera",
  "sword",
  "swords",
  "syringe",
  "table",
  "table-2",
  "table-cells-merge",
  "table-cells-split",
  "table-columns-split",
  "table-properties",
  "table-rows-split",
  "tablet",
  "tablet-smartphone",
  "tablets",
  "tag",
  "tags",
  "tally-1",
  "tally-2",
  "tally-3",
  "tally-4",
  "tally-5",
  "tangent",
  "target",
  "telescope",
  "tent",
  "tent-tree",
  "terminal",
  "terminal-square",
  "test-tube",
  "test-tube-2",
  "test-tubes",
  "text",
  "text-cursor",
  "text-cursor-input",
  "text-quote",
  "text-search",
  "text-select",
  "theater",
  "thermometer",
  "thermometer-snowflake",
  "thermometer-sun",
  "thumbs-down",
  "thumbs-up",
  "ticket",
  "ticket-check",
  "ticket-minus",
  "ticket-percent",
  "ticket-plus",
  "ticket-slash",
  "ticket-x",
  "timer",
  "timer-off",
  "timer-reset",
  "toggle-left",
  "toggle-right",
  "tornado",
  "torus",
  "touchpad",
  "touchpad-off",
  "tower-control",
  "toy-brick",
  "tractor",
  "traffic-cone",
  "train-front",
  "train-front-tunnel",
  "train-track",
  "tram-front",
  "trash",
  "trash-2",
  "tree-deciduous",
  "tree-pine",
  "trees",
  "trello",
  "trending-down",
  "trending-up",
  "triangle",
  "triangle-right",
  "trophy",
  "truck",
  "turtle",
  "tv",
  "tv-2",
  "twitch",
  "twitter",
  "type",
  "umbrella",
  "umbrella-off",
  "underline",
  "undo",
  "undo-2",
  "undo-dot",
  "unfold-horizontal",
  "unfold-vertical",
  "ungroup",
  "unlink",
  "unlink-2",
  "unlock",
  "unlock-keyhole",
  "unplug",
  "upload",
  "upload-cloud",
  "usb",
  "user",
  "user-check",
  "user-cog",
  "user-minus",
  "user-plus",
  "user-round",
  "user-round-check",
  "user-round-cog",
  "user-round-minus",
  "user-round-plus",
  "user-round-search",
  "user-round-x",
  "user-search",
  "user-x",
  "users",
  "users-round",
  "utensils",
  "utensils-crossed",
  "utility-pole",
  "variable",
  "vault",
  "vegan",
  "venetian-mask",
  "vibrate",
  "vibrate-off",
  "video",
  "video-off",
  "videotape",
  "view",
  "voicemail",
  "volume",
  "volume-1",
  "volume-2",
  "volume-x",
  "vote",
  "wallet",
  "wallet-2",
  "wallet-cards",
  "wallpaper",
  "wand",
  "wand-2",
  "warehouse",
  "washing-machine",
  "watch",
  "waves",
  "waypoints",
  "webcam",
  "webhook",
  "webhook-off",
  "weight",
  "wheat",
  "wheat-off",
  "whole-word",
  "wifi",
  "wifi-off",
  "wind",
  "wine",
  "wine-off",
  "workflow",
  "wrap-text",
  "wrench",
  "x",
  "x-circle",
  "x-octagon",
  "x-square",
  "youtube",
  "zap",
  "zap-off",
  "zoom-in",
  "zoom-out"
];

// src/modal.ts
var CommandSuggestModal = class extends import_obsidian.FuzzySuggestModal {
  constructor(app, onSelect) {
    super(app);
    this.onSelect = onSelect;
    this.setPlaceholder("Type to search for a command...");
    this.setInstructions([
      { command: "\u2191\u2193", purpose: "Navigate" },
      { command: "\u21B5", purpose: "Select command" },
      { command: "esc", purpose: "Close" }
    ]);
  }
  getItems() {
    return this.app.commands.listCommands();
  }
  getItemText(command) {
    return command.name;
  }
  onChooseItem(command) {
    this.onSelect(command);
  }
};
var IconSuggestModal = class extends import_obsidian.FuzzySuggestModal {
  constructor(app, onSelect) {
    super(app);
    this.onSelect = onSelect;
    this.setPlaceholder("Type to search for an icon...");
    this.setInstructions([
      { command: "\u2191\u2193", purpose: "Navigate" },
      { command: "\u21B5", purpose: "Select icon" },
      { command: "esc", purpose: "Close" }
    ]);
  }
  getItems() {
    return ICON_LIST;
  }
  getItemText(icon) {
    return icon;
  }
  renderSuggestion(item, el) {
    const icon = item.item;
    const wrapper = el.createSpan({ cls: "sm-icon-suggestion" });
    wrapper.style.display = "flex";
    wrapper.style.alignItems = "center";
    wrapper.style.gap = "8px";
    const iconEl = wrapper.createSpan();
    iconEl.style.width = "16px";
    iconEl.style.height = "16px";
    iconEl.style.flexShrink = "0";
    iconEl.style.overflow = "hidden";
    iconEl.style.display = "flex";
    iconEl.style.alignItems = "center";
    iconEl.style.justifyContent = "center";
    try {
      (0, import_obsidian.setIcon)(iconEl, icon);
    } catch (e) {
    }
    wrapper.createSpan({ text: icon });
  }
  onChooseItem(icon) {
    this.onSelect(icon);
  }
};

// src/settings.ts
var DEFAULT_SETTINGS = {
  profiles: [
    {
      name: "Main",
      modifiers: { alt: true, ctrl: false, shift: false, meta: false },
      submenus: [],
      mainMenuCommands: []
    }
  ]
};
var ScriptMenusSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Script Menus Settings" });
    containerEl.createEl("p", {
      text: "Right-click with a modifier key in the editor to open a custom menu with your commands. If no modifier matches, the default Obsidian context menu appears.",
      cls: "setting-item-description"
    });
    this.renderProfiles();
  }
  renderProfiles() {
    const { containerEl } = this;
    const profiles = this.plugin.settings.profiles;
    containerEl.createEl("h3", { text: "Menu Profiles" });
    const profilesContainer = containerEl.createDiv();
    profilesContainer.style.marginBottom = "16px";
    for (let i = 0; i < profiles.length; i++) {
      this.renderProfileCard(profilesContainer, i);
    }
    if (profiles.length < 8) {
      const addRow = containerEl.createDiv();
      addRow.style.marginTop = "8px";
      const addBtn = addRow.createEl("button", { text: "+ Add profile" });
      addBtn.onclick = async () => {
        const usedModifiers = new Set(
          profiles.map((p) => `${p.modifiers.alt}/${p.modifiers.ctrl}/${p.modifiers.shift}/${p.modifiers.meta}`)
        );
        let combo = { alt: false, ctrl: false, shift: false, meta: false };
        for (const m of ["shift", "ctrl", "alt", "meta"]) {
          const test = { alt: false, ctrl: false, shift: false, meta: false };
          test[m] = true;
          if (!usedModifiers.has(`${test.alt}/${test.ctrl}/${test.shift}/${test.meta}`)) {
            combo = test;
            break;
          }
        }
        this.plugin.settings.profiles = [
          ...this.plugin.settings.profiles,
          { name: `Profile ${profiles.length + 1}`, modifiers: combo, submenus: {}, mainMenuCommands: [] }
        ];
        await this.plugin.saveSettings();
        this.display();
      };
    }
  }
  renderProfileCard(container, index) {
    const profile = this.plugin.settings.profiles[index];
    const card = container.createDiv();
    card.style.cssText = `
      border: 1px solid var(--background-modifier-border);
      border-radius: 6px;
      padding: 12px;
      margin-bottom: 12px;
    `;
    const header = card.createDiv();
    header.style.cssText = "display: flex; align-items: center; gap: 8px; margin-bottom: 12px;";
    const nameInput = header.createEl("input", { type: "text", value: profile.name });
    nameInput.style.cssText = "flex: 1; font-weight: bold; background: var(--background-primary);";
    nameInput.placeholder = "Profile name";
    nameInput.onchange = async () => {
      this.plugin.settings.profiles[index].name = nameInput.value;
      await this.plugin.saveSettings();
    };
    if (this.plugin.settings.profiles.length > 1) {
      const removeBtn = header.createEl("button", { text: "\xD7 Remove" });
      removeBtn.style.cssText = "background: transparent; border: none; cursor: pointer; color: var(--text-muted); font-size: 12px;";
      removeBtn.onclick = async () => {
        this.plugin.settings.profiles = [
          ...this.plugin.settings.profiles.slice(0, index),
          ...this.plugin.settings.profiles.slice(index + 1)
        ];
        await this.plugin.saveSettings();
        this.display();
      };
    }
    const modLabel = card.createEl("span", { text: "Modifier combination:" });
    modLabel.style.cssText = "font-size: 12px; color: var(--text-muted); margin-bottom: 6px; display: block;";
    const modRow = card.createDiv();
    modRow.style.cssText = "display: flex; gap: 16px; margin-bottom: 16px;";
    const renderModCheckbox = (label, key) => {
      const labelEl = modRow.createEl("label");
      labelEl.style.cssText = "display: flex; align-items: center; gap: 4px; cursor: pointer; font-size: 13px;";
      const cb = labelEl.createEl("input", { type: "checkbox" });
      cb.checked = profile.modifiers[key];
      cb.onchange = async () => {
        this.plugin.settings.profiles[index].modifiers[key] = cb.checked;
        await this.plugin.saveSettings();
      };
      labelEl.append(` ${label}`);
    };
    renderModCheckbox("Alt", "alt");
    renderModCheckbox("Ctrl", "ctrl");
    renderModCheckbox("Shift", "shift");
    renderModCheckbox("Meta", "meta");
    this.renderSubmenus(card, index);
    this.renderMainCommands(card, index);
  }
  renderSubmenus(container, profileIndex) {
    const profile = this.plugin.settings.profiles[profileIndex];
    container.createEl("h4", { text: "Submenus" });
    const desc = container.createEl("p", {
      text: "Named groups shown as submenus in the menu.",
      cls: "setting-item-description"
    });
    const sectionContainer = container.createDiv();
    sectionContainer.style.marginBottom = "8px";
    const renderSubmenuSections = () => {
      const existing = sectionContainer.querySelectorAll(".sm-submenu-section");
      Array.from(existing).forEach((el) => el.remove());
      for (let si = 0; si < profile.submenus.length; si++) {
        const section = profile.submenus[si];
        const sectionDiv = sectionContainer.createDiv();
        sectionDiv.className = "sm-submenu-section";
        sectionDiv.style.cssText = "margin-bottom: 8px; border: 1px solid var(--background-modifier-border); border-radius: 4px; padding: 8px;";
        const headerRow = sectionDiv.createDiv();
        headerRow.style.cssText = "display: flex; gap: 8px; align-items: center; margin-bottom: 8px;";
        const iconBtn = headerRow.createEl("button");
        iconBtn.style.cssText = "width: 24px; height: 24px; display: flex; align-items: center; justify-content: center; background: transparent; border: 1px solid var(--background-modifier-border); border-radius: 4px; cursor: pointer; color: var(--text-muted); flex-shrink: 0; font-size: 11px;";
        iconBtn.title = "Section icon";
        const renderSectionIcon = () => {
          iconBtn.empty();
          if (section.icon) {
            (0, import_obsidian2.setIcon)(iconBtn, section.icon);
          } else {
            iconBtn.setText("\u25CE");
          }
        };
        renderSectionIcon();
        iconBtn.onclick = () => {
          new IconSuggestModal(this.app, (iconName) => {
            section.icon = iconName;
            profile.submenus = [...profile.submenus];
            renderSectionIcon();
            this.plugin.saveSettings();
          }).open();
        };
        const colorInput = headerRow.createEl("input", { type: "color" });
        colorInput.value = section.color || "#000000";
        colorInput.title = "Section color";
        colorInput.style.cssText = "width: 22px; height: 22px; padding: 0; border: none; border-radius: 4px; cursor: pointer; background: none; flex-shrink: 0;";
        colorInput.onchange = () => {
          section.color = colorInput.value;
          this.plugin.saveSettings();
        };
        const clearColorBtn = headerRow.createEl("button", { text: "\xD7" });
        clearColorBtn.title = "Clear color";
        clearColorBtn.style.cssText = "width: 18px; height: 22px; padding: 0; border: none; background: transparent; cursor: pointer; color: var(--text-muted); font-size: 12px; flex-shrink: 0; display: flex; align-items: center; justify-content: center;";
        clearColorBtn.onclick = async () => {
          section.color = void 0;
          colorInput.value = "#000000";
          this.plugin.saveSettings();
        };
        const title = headerRow.createEl("input", { type: "text", value: section.label });
        title.style.cssText = "font-weight: bold; flex: 1; background: var(--background-primary);";
        title.placeholder = "Section name";
        title.onchange = async () => {
          section.label = title.value;
          await this.plugin.saveSettings();
        };
        const removeBtn = headerRow.createEl("button", { text: "\xD7" });
        removeBtn.style.cssText = "background: transparent; border: none; cursor: pointer; color: var(--text-muted); font-size: 14px;";
        removeBtn.title = "Remove section";
        removeBtn.onclick = async () => {
          profile.submenus = profile.submenus.filter((_, i) => i !== si);
          await this.plugin.saveSettings();
          renderSubmenuSections();
        };
        const entriesDiv = sectionDiv.createDiv();
        const sectionEntries = section.entries;
        for (let i = 0; i < sectionEntries.length; i++) {
          this.renderEntryRow(entriesDiv, sectionEntries, i, () => profile.submenus[si].entries, renderSubmenuSections);
        }
        const addCmdRow = sectionDiv.createDiv();
        addCmdRow.style.cssText = "display: flex; gap: 8px; margin-top: 4px;";
        const addCmdBtn = addCmdRow.createEl("button", { text: "+ Add command" });
        addCmdBtn.onclick = async () => {
          sectionEntries.push({ label: "New command", commandId: "" });
          profile.submenus = [...profile.submenus];
          await this.plugin.saveSettings();
          renderSubmenuSections();
        };
        const addSepBtn = addCmdRow.createEl("button", { text: "+ Separator" });
        addSepBtn.onclick = async () => {
          sectionEntries.push({ label: "", commandId: "", isSeparator: true });
          profile.submenus = [...profile.submenus];
          await this.plugin.saveSettings();
          renderSubmenuSections();
        };
      }
    };
    const addSectionRow = sectionContainer.createDiv();
    addSectionRow.style.cssText = "display: flex; gap: 8px; align-items: center; margin-bottom: 12px;";
    const sectionNameInput = addSectionRow.createEl("input", { type: "text" });
    sectionNameInput.placeholder = "Section name (e.g. Utils, Format...)";
    sectionNameInput.style.cssText = "flex: 1; background: var(--background-primary);";
    const addBtn = addSectionRow.createEl("button", { text: "+ Add section" });
    addBtn.onclick = async () => {
      const name = sectionNameInput.value.trim();
      if (!name)
        return;
      if (profile.submenus.some((s) => s.label === name))
        return;
      profile.submenus = [...profile.submenus, { label: name, entries: [] }];
      await this.plugin.saveSettings();
      sectionNameInput.value = "";
      renderSubmenuSections();
    };
    renderSubmenuSections();
  }
  renderMainCommands(container, profileIndex) {
    const profile = this.plugin.settings.profiles[profileIndex];
    container.createEl("h4", { text: "Main commands" });
    container.createEl("p", {
      text: "Commands shown at the top of the menu, outside any submenu.",
      cls: "setting-item-description"
    });
    const cmdContainer = container.createDiv();
    cmdContainer.style.marginBottom = "8px";
    const render = () => {
      cmdContainer.empty();
      const list = this.plugin.settings.profiles[profileIndex].mainMenuCommands;
      for (let i = 0; i < list.length; i++) {
        this.renderEntryRow(cmdContainer, list, i, () => this.plugin.settings.profiles[profileIndex].mainMenuCommands, render);
      }
      const addRow = cmdContainer.createDiv();
      addRow.style.cssText = "display: flex; gap: 8px; margin-top: 8px;";
      const addBtn = addRow.createEl("button", { text: "+ Add command" });
      addBtn.onclick = async () => {
        this.plugin.settings.profiles[profileIndex].mainMenuCommands = [
          ...this.plugin.settings.profiles[profileIndex].mainMenuCommands,
          { label: "New command", commandId: "" }
        ];
        await this.plugin.saveSettings();
        render();
      };
      const addSepBtn = addRow.createEl("button", { text: "+ Separator" });
      addSepBtn.onclick = async () => {
        this.plugin.settings.profiles[profileIndex].mainMenuCommands = [
          ...this.plugin.settings.profiles[profileIndex].mainMenuCommands,
          { label: "", commandId: "", isSeparator: true }
        ];
        await this.plugin.saveSettings();
        render();
      };
    };
    render();
  }
  renderEntryRow(container, list, index, getList, onRemove) {
    const entry = list[index];
    const swap = (i, j) => {
      const tmp = list[i];
      list[i] = list[j];
      list[j] = tmp;
    };
    const createMoveButtons = (row2) => {
      const moveUp = row2.createEl("button", { text: "\u25B2" });
      moveUp.style.cssText = "width: 22px; height: 22px; padding: 0; border: 1px solid var(--background-modifier-border); border-radius: 3px; background: transparent; cursor: pointer; color: var(--text-muted); font-size: 10px; flex-shrink: 0; display: flex; align-items: center; justify-content: center;";
      moveUp.title = "Move up";
      moveUp.disabled = index === 0;
      moveUp.onclick = async () => {
        swap(index, index - 1);
        await this.plugin.saveSettings();
        if (onRemove)
          onRemove();
      };
      const moveDown = row2.createEl("button", { text: "\u25BC" });
      moveDown.style.cssText = "width: 22px; height: 22px; padding: 0; border: 1px solid var(--background-modifier-border); border-radius: 3px; background: transparent; cursor: pointer; color: var(--text-muted); font-size: 10px; flex-shrink: 0; display: flex; align-items: center; justify-content: center;";
      moveDown.title = "Move down";
      moveDown.disabled = index === list.length - 1;
      moveDown.onclick = async () => {
        swap(index, index + 1);
        await this.plugin.saveSettings();
        if (onRemove)
          onRemove();
      };
    };
    if (entry.isSeparator) {
      const row2 = container.createDiv();
      row2.style.cssText = "display: flex; gap: 8px; align-items: center; margin-bottom: 4px;";
      createMoveButtons(row2);
      const sepIcon = row2.createSpan();
      sepIcon.style.cssText = "width: 28px; height: 28px; display: flex; align-items: center; justify-content: center; flex-shrink: 0; color: var(--text-muted);";
      sepIcon.setText("\u2014");
      const sepLabel = row2.createEl("span", { text: "Separator" });
      sepLabel.style.cssText = "flex: 1; color: var(--text-muted); font-size: 12px; font-style: italic;";
      const removeBtn2 = row2.createEl("button", { text: "\xD7" });
      removeBtn2.style.cssText = "background: transparent; border: none; cursor: pointer; color: var(--text-muted);";
      removeBtn2.onclick = async () => {
        const updated = [...list.slice(0, index), ...list.slice(index + 1)];
        for (let j = 0; j < updated.length; j++)
          list[j] = updated[j];
        list.length = updated.length;
        await this.plugin.saveSettings();
        if (onRemove)
          onRemove();
      };
      return;
    }
    const row = container.createDiv();
    row.style.cssText = "display: flex; gap: 8px; align-items: center; margin-bottom: 4px;";
    createMoveButtons(row);
    const labelInput = row.createEl("input", { type: "text" });
    labelInput.value = list[index].label;
    labelInput.style.cssText = "flex: 1; background: var(--background-primary);";
    labelInput.placeholder = "Label (e.g. My script)";
    const iconBtn = row.createEl("button");
    iconBtn.style.cssText = "width: 28px; height: 28px; display: flex; align-items: center; justify-content: center; background: transparent; border: 1px solid var(--background-modifier-border); border-radius: 4px; cursor: pointer; color: var(--text-muted); flex-shrink: 0;";
    iconBtn.title = "Choose icon";
    const renderIcon = () => {
      iconBtn.empty();
      if (list[index].icon) {
        (0, import_obsidian2.setIcon)(iconBtn, list[index].icon);
      } else {
        iconBtn.setText("?");
      }
    };
    renderIcon();
    iconBtn.onclick = () => {
      new IconSuggestModal(this.app, (iconName) => {
        list[index].icon = iconName;
        getList();
        renderIcon();
        this.plugin.saveSettings();
      }).open();
    };
    const colorInput = row.createEl("input", { type: "color" });
    colorInput.value = list[index].color || "#000000";
    colorInput.title = "Item color";
    colorInput.style.cssText = "width: 24px; height: 24px; padding: 0; border: none; border-radius: 4px; cursor: pointer; background: none; flex-shrink: 0;";
    colorInput.onchange = () => {
      list[index].color = colorInput.value;
      this.plugin.saveSettings();
    };
    const clearColorBtn = row.createEl("button", { text: "\xD7" });
    clearColorBtn.title = "Clear color";
    clearColorBtn.style.cssText = "width: 20px; height: 24px; padding: 0; border: none; background: transparent; cursor: pointer; color: var(--text-muted); font-size: 14px; flex-shrink: 0; display: flex; align-items: center; justify-content: center;";
    clearColorBtn.onclick = async () => {
      list[index].color = void 0;
      colorInput.value = "#000000";
      this.plugin.saveSettings();
    };
    const cmdInput = row.createEl("input", { type: "text" });
    cmdInput.value = list[index].commandId;
    cmdInput.style.cssText = "flex: 1; background: var(--background-primary);";
    cmdInput.placeholder = "Command ID (e.g. my-plugin:action)";
    const searchBtn = row.createEl("button", { text: "Find..." });
    searchBtn.style.cssText = "background: transparent; border: none; cursor: pointer; color: var(--text-muted); font-size: 12px;";
    searchBtn.title = "Search for a command";
    searchBtn.onclick = () => {
      new CommandSuggestModal(this.app, (command) => {
        labelInput.value = command.name;
        cmdInput.value = command.id;
        list[index].label = command.name;
        list[index].commandId = command.id;
        this.plugin.saveSettings();
      }).open();
    };
    const removeBtn = row.createEl("button", { text: "\xD7" });
    removeBtn.style.cssText = "background: transparent; border: none; cursor: pointer; color: var(--text-muted);";
    removeBtn.onclick = async () => {
      const updated = [...list.slice(0, index), ...list.slice(index + 1)];
      for (let j = 0; j < updated.length; j++)
        list[j] = updated[j];
      list.length = updated.length;
      await this.plugin.saveSettings();
      if (onRemove)
        onRemove();
    };
    labelInput.onchange = async () => {
      list[index].label = labelInput.value;
      await this.plugin.saveSettings();
    };
    cmdInput.onchange = async () => {
      list[index].commandId = cmdInput.value;
      await this.plugin.saveSettings();
    };
  }
};

// src/context-menu.ts
var import_obsidian3 = require("obsidian");

// node_modules/@floating-ui/utils/dist/floating-ui.utils.mjs
var min = Math.min;
var max = Math.max;
var round = Math.round;
var createCoords = (v) => ({
  x: v,
  y: v
});
var oppositeSideMap = {
  left: "right",
  right: "left",
  bottom: "top",
  top: "bottom"
};
function clamp(start, value, end) {
  return max(start, min(value, end));
}
function evaluate(value, param) {
  return typeof value === "function" ? value(param) : value;
}
function getSide(placement) {
  return placement.split("-")[0];
}
function getAlignment(placement) {
  return placement.split("-")[1];
}
function getOppositeAxis(axis) {
  return axis === "x" ? "y" : "x";
}
function getAxisLength(axis) {
  return axis === "y" ? "height" : "width";
}
function getSideAxis(placement) {
  const firstChar = placement[0];
  return firstChar === "t" || firstChar === "b" ? "y" : "x";
}
function getAlignmentAxis(placement) {
  return getOppositeAxis(getSideAxis(placement));
}
function getAlignmentSides(placement, rects, rtl) {
  if (rtl === void 0) {
    rtl = false;
  }
  const alignment = getAlignment(placement);
  const alignmentAxis = getAlignmentAxis(placement);
  const length = getAxisLength(alignmentAxis);
  let mainAlignmentSide = alignmentAxis === "x" ? alignment === (rtl ? "end" : "start") ? "right" : "left" : alignment === "start" ? "bottom" : "top";
  if (rects.reference[length] > rects.floating[length]) {
    mainAlignmentSide = getOppositePlacement(mainAlignmentSide);
  }
  return [mainAlignmentSide, getOppositePlacement(mainAlignmentSide)];
}
function getExpandedPlacements(placement) {
  const oppositePlacement = getOppositePlacement(placement);
  return [getOppositeAlignmentPlacement(placement), oppositePlacement, getOppositeAlignmentPlacement(oppositePlacement)];
}
function getOppositeAlignmentPlacement(placement) {
  return placement.includes("start") ? placement.replace("start", "end") : placement.replace("end", "start");
}
var lrPlacement = ["left", "right"];
var rlPlacement = ["right", "left"];
var tbPlacement = ["top", "bottom"];
var btPlacement = ["bottom", "top"];
function getSideList(side, isStart, rtl) {
  switch (side) {
    case "top":
    case "bottom":
      if (rtl)
        return isStart ? rlPlacement : lrPlacement;
      return isStart ? lrPlacement : rlPlacement;
    case "left":
    case "right":
      return isStart ? tbPlacement : btPlacement;
    default:
      return [];
  }
}
function getOppositeAxisPlacements(placement, flipAlignment, direction, rtl) {
  const alignment = getAlignment(placement);
  let list = getSideList(getSide(placement), direction === "start", rtl);
  if (alignment) {
    list = list.map((side) => side + "-" + alignment);
    if (flipAlignment) {
      list = list.concat(list.map(getOppositeAlignmentPlacement));
    }
  }
  return list;
}
function getOppositePlacement(placement) {
  const side = getSide(placement);
  return oppositeSideMap[side] + placement.slice(side.length);
}
function expandPaddingObject(padding) {
  return {
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    ...padding
  };
}
function getPaddingObject(padding) {
  return typeof padding !== "number" ? expandPaddingObject(padding) : {
    top: padding,
    right: padding,
    bottom: padding,
    left: padding
  };
}
function rectToClientRect(rect) {
  const {
    x,
    y,
    width,
    height
  } = rect;
  return {
    width,
    height,
    top: y,
    left: x,
    right: x + width,
    bottom: y + height,
    x,
    y
  };
}

// node_modules/@floating-ui/core/dist/floating-ui.core.mjs
function computeCoordsFromPlacement(_ref, placement, rtl) {
  let {
    reference,
    floating
  } = _ref;
  const sideAxis = getSideAxis(placement);
  const alignmentAxis = getAlignmentAxis(placement);
  const alignLength = getAxisLength(alignmentAxis);
  const side = getSide(placement);
  const isVertical = sideAxis === "y";
  const commonX = reference.x + reference.width / 2 - floating.width / 2;
  const commonY = reference.y + reference.height / 2 - floating.height / 2;
  const commonAlign = reference[alignLength] / 2 - floating[alignLength] / 2;
  let coords;
  switch (side) {
    case "top":
      coords = {
        x: commonX,
        y: reference.y - floating.height
      };
      break;
    case "bottom":
      coords = {
        x: commonX,
        y: reference.y + reference.height
      };
      break;
    case "right":
      coords = {
        x: reference.x + reference.width,
        y: commonY
      };
      break;
    case "left":
      coords = {
        x: reference.x - floating.width,
        y: commonY
      };
      break;
    default:
      coords = {
        x: reference.x,
        y: reference.y
      };
  }
  switch (getAlignment(placement)) {
    case "start":
      coords[alignmentAxis] -= commonAlign * (rtl && isVertical ? -1 : 1);
      break;
    case "end":
      coords[alignmentAxis] += commonAlign * (rtl && isVertical ? -1 : 1);
      break;
  }
  return coords;
}
async function detectOverflow(state, options) {
  var _await$platform$isEle;
  if (options === void 0) {
    options = {};
  }
  const {
    x,
    y,
    platform: platform2,
    rects,
    elements,
    strategy
  } = state;
  const {
    boundary = "clippingAncestors",
    rootBoundary = "viewport",
    elementContext = "floating",
    altBoundary = false,
    padding = 0
  } = evaluate(options, state);
  const paddingObject = getPaddingObject(padding);
  const altContext = elementContext === "floating" ? "reference" : "floating";
  const element = elements[altBoundary ? altContext : elementContext];
  const clippingClientRect = rectToClientRect(await platform2.getClippingRect({
    element: ((_await$platform$isEle = await (platform2.isElement == null ? void 0 : platform2.isElement(element))) != null ? _await$platform$isEle : true) ? element : element.contextElement || await (platform2.getDocumentElement == null ? void 0 : platform2.getDocumentElement(elements.floating)),
    boundary,
    rootBoundary,
    strategy
  }));
  const rect = elementContext === "floating" ? {
    x,
    y,
    width: rects.floating.width,
    height: rects.floating.height
  } : rects.reference;
  const offsetParent = await (platform2.getOffsetParent == null ? void 0 : platform2.getOffsetParent(elements.floating));
  const offsetScale = await (platform2.isElement == null ? void 0 : platform2.isElement(offsetParent)) ? await (platform2.getScale == null ? void 0 : platform2.getScale(offsetParent)) || {
    x: 1,
    y: 1
  } : {
    x: 1,
    y: 1
  };
  const elementClientRect = rectToClientRect(platform2.convertOffsetParentRelativeRectToViewportRelativeRect ? await platform2.convertOffsetParentRelativeRectToViewportRelativeRect({
    elements,
    rect,
    offsetParent,
    strategy
  }) : rect);
  return {
    top: (clippingClientRect.top - elementClientRect.top + paddingObject.top) / offsetScale.y,
    bottom: (elementClientRect.bottom - clippingClientRect.bottom + paddingObject.bottom) / offsetScale.y,
    left: (clippingClientRect.left - elementClientRect.left + paddingObject.left) / offsetScale.x,
    right: (elementClientRect.right - clippingClientRect.right + paddingObject.right) / offsetScale.x
  };
}
var MAX_RESET_COUNT = 50;
var computePosition = async (reference, floating, config) => {
  const {
    placement = "bottom",
    strategy = "absolute",
    middleware = [],
    platform: platform2
  } = config;
  const platformWithDetectOverflow = platform2.detectOverflow ? platform2 : {
    ...platform2,
    detectOverflow
  };
  const rtl = await (platform2.isRTL == null ? void 0 : platform2.isRTL(floating));
  let rects = await platform2.getElementRects({
    reference,
    floating,
    strategy
  });
  let {
    x,
    y
  } = computeCoordsFromPlacement(rects, placement, rtl);
  let statefulPlacement = placement;
  let resetCount = 0;
  const middlewareData = {};
  for (let i = 0; i < middleware.length; i++) {
    const currentMiddleware = middleware[i];
    if (!currentMiddleware) {
      continue;
    }
    const {
      name,
      fn
    } = currentMiddleware;
    const {
      x: nextX,
      y: nextY,
      data,
      reset
    } = await fn({
      x,
      y,
      initialPlacement: placement,
      placement: statefulPlacement,
      strategy,
      middlewareData,
      rects,
      platform: platformWithDetectOverflow,
      elements: {
        reference,
        floating
      }
    });
    x = nextX != null ? nextX : x;
    y = nextY != null ? nextY : y;
    middlewareData[name] = {
      ...middlewareData[name],
      ...data
    };
    if (reset && resetCount < MAX_RESET_COUNT) {
      resetCount++;
      if (typeof reset === "object") {
        if (reset.placement) {
          statefulPlacement = reset.placement;
        }
        if (reset.rects) {
          rects = reset.rects === true ? await platform2.getElementRects({
            reference,
            floating,
            strategy
          }) : reset.rects;
        }
        ({
          x,
          y
        } = computeCoordsFromPlacement(rects, statefulPlacement, rtl));
      }
      i = -1;
    }
  }
  return {
    x,
    y,
    placement: statefulPlacement,
    strategy,
    middlewareData
  };
};
var flip = function(options) {
  if (options === void 0) {
    options = {};
  }
  return {
    name: "flip",
    options,
    async fn(state) {
      var _middlewareData$arrow, _middlewareData$flip;
      const {
        placement,
        middlewareData,
        rects,
        initialPlacement,
        platform: platform2,
        elements
      } = state;
      const {
        mainAxis: checkMainAxis = true,
        crossAxis: checkCrossAxis = true,
        fallbackPlacements: specifiedFallbackPlacements,
        fallbackStrategy = "bestFit",
        fallbackAxisSideDirection = "none",
        flipAlignment = true,
        ...detectOverflowOptions
      } = evaluate(options, state);
      if ((_middlewareData$arrow = middlewareData.arrow) != null && _middlewareData$arrow.alignmentOffset) {
        return {};
      }
      const side = getSide(placement);
      const initialSideAxis = getSideAxis(initialPlacement);
      const isBasePlacement = getSide(initialPlacement) === initialPlacement;
      const rtl = await (platform2.isRTL == null ? void 0 : platform2.isRTL(elements.floating));
      const fallbackPlacements = specifiedFallbackPlacements || (isBasePlacement || !flipAlignment ? [getOppositePlacement(initialPlacement)] : getExpandedPlacements(initialPlacement));
      const hasFallbackAxisSideDirection = fallbackAxisSideDirection !== "none";
      if (!specifiedFallbackPlacements && hasFallbackAxisSideDirection) {
        fallbackPlacements.push(...getOppositeAxisPlacements(initialPlacement, flipAlignment, fallbackAxisSideDirection, rtl));
      }
      const placements2 = [initialPlacement, ...fallbackPlacements];
      const overflow = await platform2.detectOverflow(state, detectOverflowOptions);
      const overflows = [];
      let overflowsData = ((_middlewareData$flip = middlewareData.flip) == null ? void 0 : _middlewareData$flip.overflows) || [];
      if (checkMainAxis) {
        overflows.push(overflow[side]);
      }
      if (checkCrossAxis) {
        const sides2 = getAlignmentSides(placement, rects, rtl);
        overflows.push(overflow[sides2[0]], overflow[sides2[1]]);
      }
      overflowsData = [...overflowsData, {
        placement,
        overflows
      }];
      if (!overflows.every((side2) => side2 <= 0)) {
        var _middlewareData$flip2, _overflowsData$filter;
        const nextIndex = (((_middlewareData$flip2 = middlewareData.flip) == null ? void 0 : _middlewareData$flip2.index) || 0) + 1;
        const nextPlacement = placements2[nextIndex];
        if (nextPlacement) {
          const ignoreCrossAxisOverflow = checkCrossAxis === "alignment" ? initialSideAxis !== getSideAxis(nextPlacement) : false;
          if (!ignoreCrossAxisOverflow || // We leave the current main axis only if every placement on that axis
          // overflows the main axis.
          overflowsData.every((d) => getSideAxis(d.placement) === initialSideAxis ? d.overflows[0] > 0 : true)) {
            return {
              data: {
                index: nextIndex,
                overflows: overflowsData
              },
              reset: {
                placement: nextPlacement
              }
            };
          }
        }
        let resetPlacement = (_overflowsData$filter = overflowsData.filter((d) => d.overflows[0] <= 0).sort((a, b) => a.overflows[1] - b.overflows[1])[0]) == null ? void 0 : _overflowsData$filter.placement;
        if (!resetPlacement) {
          switch (fallbackStrategy) {
            case "bestFit": {
              var _overflowsData$filter2;
              const placement2 = (_overflowsData$filter2 = overflowsData.filter((d) => {
                if (hasFallbackAxisSideDirection) {
                  const currentSideAxis = getSideAxis(d.placement);
                  return currentSideAxis === initialSideAxis || // Create a bias to the `y` side axis due to horizontal
                  // reading directions favoring greater width.
                  currentSideAxis === "y";
                }
                return true;
              }).map((d) => [d.placement, d.overflows.filter((overflow2) => overflow2 > 0).reduce((acc, overflow2) => acc + overflow2, 0)]).sort((a, b) => a[1] - b[1])[0]) == null ? void 0 : _overflowsData$filter2[0];
              if (placement2) {
                resetPlacement = placement2;
              }
              break;
            }
            case "initialPlacement":
              resetPlacement = initialPlacement;
              break;
          }
        }
        if (placement !== resetPlacement) {
          return {
            reset: {
              placement: resetPlacement
            }
          };
        }
      }
      return {};
    }
  };
};
var originSides = /* @__PURE__ */ new Set(["left", "top"]);
async function convertValueToCoords(state, options) {
  const {
    placement,
    platform: platform2,
    elements
  } = state;
  const rtl = await (platform2.isRTL == null ? void 0 : platform2.isRTL(elements.floating));
  const side = getSide(placement);
  const alignment = getAlignment(placement);
  const isVertical = getSideAxis(placement) === "y";
  const mainAxisMulti = originSides.has(side) ? -1 : 1;
  const crossAxisMulti = rtl && isVertical ? -1 : 1;
  const rawValue = evaluate(options, state);
  let {
    mainAxis,
    crossAxis,
    alignmentAxis
  } = typeof rawValue === "number" ? {
    mainAxis: rawValue,
    crossAxis: 0,
    alignmentAxis: null
  } : {
    mainAxis: rawValue.mainAxis || 0,
    crossAxis: rawValue.crossAxis || 0,
    alignmentAxis: rawValue.alignmentAxis
  };
  if (alignment && typeof alignmentAxis === "number") {
    crossAxis = alignment === "end" ? alignmentAxis * -1 : alignmentAxis;
  }
  return isVertical ? {
    x: crossAxis * crossAxisMulti,
    y: mainAxis * mainAxisMulti
  } : {
    x: mainAxis * mainAxisMulti,
    y: crossAxis * crossAxisMulti
  };
}
var offset = function(options) {
  if (options === void 0) {
    options = 0;
  }
  return {
    name: "offset",
    options,
    async fn(state) {
      var _middlewareData$offse, _middlewareData$arrow;
      const {
        x,
        y,
        placement,
        middlewareData
      } = state;
      const diffCoords = await convertValueToCoords(state, options);
      if (placement === ((_middlewareData$offse = middlewareData.offset) == null ? void 0 : _middlewareData$offse.placement) && (_middlewareData$arrow = middlewareData.arrow) != null && _middlewareData$arrow.alignmentOffset) {
        return {};
      }
      return {
        x: x + diffCoords.x,
        y: y + diffCoords.y,
        data: {
          ...diffCoords,
          placement
        }
      };
    }
  };
};
var shift = function(options) {
  if (options === void 0) {
    options = {};
  }
  return {
    name: "shift",
    options,
    async fn(state) {
      const {
        x,
        y,
        placement,
        platform: platform2
      } = state;
      const {
        mainAxis: checkMainAxis = true,
        crossAxis: checkCrossAxis = false,
        limiter = {
          fn: (_ref) => {
            let {
              x: x2,
              y: y2
            } = _ref;
            return {
              x: x2,
              y: y2
            };
          }
        },
        ...detectOverflowOptions
      } = evaluate(options, state);
      const coords = {
        x,
        y
      };
      const overflow = await platform2.detectOverflow(state, detectOverflowOptions);
      const crossAxis = getSideAxis(getSide(placement));
      const mainAxis = getOppositeAxis(crossAxis);
      let mainAxisCoord = coords[mainAxis];
      let crossAxisCoord = coords[crossAxis];
      if (checkMainAxis) {
        const minSide = mainAxis === "y" ? "top" : "left";
        const maxSide = mainAxis === "y" ? "bottom" : "right";
        const min2 = mainAxisCoord + overflow[minSide];
        const max2 = mainAxisCoord - overflow[maxSide];
        mainAxisCoord = clamp(min2, mainAxisCoord, max2);
      }
      if (checkCrossAxis) {
        const minSide = crossAxis === "y" ? "top" : "left";
        const maxSide = crossAxis === "y" ? "bottom" : "right";
        const min2 = crossAxisCoord + overflow[minSide];
        const max2 = crossAxisCoord - overflow[maxSide];
        crossAxisCoord = clamp(min2, crossAxisCoord, max2);
      }
      const limitedCoords = limiter.fn({
        ...state,
        [mainAxis]: mainAxisCoord,
        [crossAxis]: crossAxisCoord
      });
      return {
        ...limitedCoords,
        data: {
          x: limitedCoords.x - x,
          y: limitedCoords.y - y,
          enabled: {
            [mainAxis]: checkMainAxis,
            [crossAxis]: checkCrossAxis
          }
        }
      };
    }
  };
};
var size = function(options) {
  if (options === void 0) {
    options = {};
  }
  return {
    name: "size",
    options,
    async fn(state) {
      var _state$middlewareData, _state$middlewareData2;
      const {
        placement,
        rects,
        platform: platform2,
        elements
      } = state;
      const {
        apply = () => {
        },
        ...detectOverflowOptions
      } = evaluate(options, state);
      const overflow = await platform2.detectOverflow(state, detectOverflowOptions);
      const side = getSide(placement);
      const alignment = getAlignment(placement);
      const isYAxis = getSideAxis(placement) === "y";
      const {
        width,
        height
      } = rects.floating;
      let heightSide;
      let widthSide;
      if (side === "top" || side === "bottom") {
        heightSide = side;
        widthSide = alignment === (await (platform2.isRTL == null ? void 0 : platform2.isRTL(elements.floating)) ? "start" : "end") ? "left" : "right";
      } else {
        widthSide = side;
        heightSide = alignment === "end" ? "top" : "bottom";
      }
      const maximumClippingHeight = height - overflow.top - overflow.bottom;
      const maximumClippingWidth = width - overflow.left - overflow.right;
      const overflowAvailableHeight = min(height - overflow[heightSide], maximumClippingHeight);
      const overflowAvailableWidth = min(width - overflow[widthSide], maximumClippingWidth);
      const noShift = !state.middlewareData.shift;
      let availableHeight = overflowAvailableHeight;
      let availableWidth = overflowAvailableWidth;
      if ((_state$middlewareData = state.middlewareData.shift) != null && _state$middlewareData.enabled.x) {
        availableWidth = maximumClippingWidth;
      }
      if ((_state$middlewareData2 = state.middlewareData.shift) != null && _state$middlewareData2.enabled.y) {
        availableHeight = maximumClippingHeight;
      }
      if (noShift && !alignment) {
        const xMin = max(overflow.left, 0);
        const xMax = max(overflow.right, 0);
        const yMin = max(overflow.top, 0);
        const yMax = max(overflow.bottom, 0);
        if (isYAxis) {
          availableWidth = width - 2 * (xMin !== 0 || xMax !== 0 ? xMin + xMax : max(overflow.left, overflow.right));
        } else {
          availableHeight = height - 2 * (yMin !== 0 || yMax !== 0 ? yMin + yMax : max(overflow.top, overflow.bottom));
        }
      }
      await apply({
        ...state,
        availableWidth,
        availableHeight
      });
      const nextDimensions = await platform2.getDimensions(elements.floating);
      if (width !== nextDimensions.width || height !== nextDimensions.height) {
        return {
          reset: {
            rects: true
          }
        };
      }
      return {};
    }
  };
};

// node_modules/@floating-ui/utils/dist/floating-ui.utils.dom.mjs
function hasWindow() {
  return typeof window !== "undefined";
}
function getNodeName(node) {
  if (isNode(node)) {
    return (node.nodeName || "").toLowerCase();
  }
  return "#document";
}
function getWindow(node) {
  var _node$ownerDocument;
  return (node == null || (_node$ownerDocument = node.ownerDocument) == null ? void 0 : _node$ownerDocument.defaultView) || window;
}
function getDocumentElement(node) {
  var _ref;
  return (_ref = (isNode(node) ? node.ownerDocument : node.document) || window.document) == null ? void 0 : _ref.documentElement;
}
function isNode(value) {
  if (!hasWindow()) {
    return false;
  }
  return value instanceof Node || value instanceof getWindow(value).Node;
}
function isElement(value) {
  if (!hasWindow()) {
    return false;
  }
  return value instanceof Element || value instanceof getWindow(value).Element;
}
function isHTMLElement(value) {
  if (!hasWindow()) {
    return false;
  }
  return value instanceof HTMLElement || value instanceof getWindow(value).HTMLElement;
}
function isShadowRoot(value) {
  if (!hasWindow() || typeof ShadowRoot === "undefined") {
    return false;
  }
  return value instanceof ShadowRoot || value instanceof getWindow(value).ShadowRoot;
}
function isOverflowElement(element) {
  const {
    overflow,
    overflowX,
    overflowY,
    display
  } = getComputedStyle2(element);
  return /auto|scroll|overlay|hidden|clip/.test(overflow + overflowY + overflowX) && display !== "inline" && display !== "contents";
}
function isTableElement(element) {
  return /^(table|td|th)$/.test(getNodeName(element));
}
function isTopLayer(element) {
  try {
    if (element.matches(":popover-open")) {
      return true;
    }
  } catch (_e) {
  }
  try {
    return element.matches(":modal");
  } catch (_e) {
    return false;
  }
}
var willChangeRe = /transform|translate|scale|rotate|perspective|filter/;
var containRe = /paint|layout|strict|content/;
var isNotNone = (value) => !!value && value !== "none";
var isWebKitValue;
function isContainingBlock(elementOrCss) {
  const css = isElement(elementOrCss) ? getComputedStyle2(elementOrCss) : elementOrCss;
  return isNotNone(css.transform) || isNotNone(css.translate) || isNotNone(css.scale) || isNotNone(css.rotate) || isNotNone(css.perspective) || !isWebKit() && (isNotNone(css.backdropFilter) || isNotNone(css.filter)) || willChangeRe.test(css.willChange || "") || containRe.test(css.contain || "");
}
function getContainingBlock(element) {
  let currentNode = getParentNode(element);
  while (isHTMLElement(currentNode) && !isLastTraversableNode(currentNode)) {
    if (isContainingBlock(currentNode)) {
      return currentNode;
    } else if (isTopLayer(currentNode)) {
      return null;
    }
    currentNode = getParentNode(currentNode);
  }
  return null;
}
function isWebKit() {
  if (isWebKitValue == null) {
    isWebKitValue = typeof CSS !== "undefined" && CSS.supports && CSS.supports("-webkit-backdrop-filter", "none");
  }
  return isWebKitValue;
}
function isLastTraversableNode(node) {
  return /^(html|body|#document)$/.test(getNodeName(node));
}
function getComputedStyle2(element) {
  return getWindow(element).getComputedStyle(element);
}
function getNodeScroll(element) {
  if (isElement(element)) {
    return {
      scrollLeft: element.scrollLeft,
      scrollTop: element.scrollTop
    };
  }
  return {
    scrollLeft: element.scrollX,
    scrollTop: element.scrollY
  };
}
function getParentNode(node) {
  if (getNodeName(node) === "html") {
    return node;
  }
  const result = (
    // Step into the shadow DOM of the parent of a slotted node.
    node.assignedSlot || // DOM Element detected.
    node.parentNode || // ShadowRoot detected.
    isShadowRoot(node) && node.host || // Fallback.
    getDocumentElement(node)
  );
  return isShadowRoot(result) ? result.host : result;
}
function getNearestOverflowAncestor(node) {
  const parentNode = getParentNode(node);
  if (isLastTraversableNode(parentNode)) {
    return node.ownerDocument ? node.ownerDocument.body : node.body;
  }
  if (isHTMLElement(parentNode) && isOverflowElement(parentNode)) {
    return parentNode;
  }
  return getNearestOverflowAncestor(parentNode);
}
function getOverflowAncestors(node, list, traverseIframes) {
  var _node$ownerDocument2;
  if (list === void 0) {
    list = [];
  }
  if (traverseIframes === void 0) {
    traverseIframes = true;
  }
  const scrollableAncestor = getNearestOverflowAncestor(node);
  const isBody = scrollableAncestor === ((_node$ownerDocument2 = node.ownerDocument) == null ? void 0 : _node$ownerDocument2.body);
  const win = getWindow(scrollableAncestor);
  if (isBody) {
    const frameElement = getFrameElement(win);
    return list.concat(win, win.visualViewport || [], isOverflowElement(scrollableAncestor) ? scrollableAncestor : [], frameElement && traverseIframes ? getOverflowAncestors(frameElement) : []);
  } else {
    return list.concat(scrollableAncestor, getOverflowAncestors(scrollableAncestor, [], traverseIframes));
  }
}
function getFrameElement(win) {
  return win.parent && Object.getPrototypeOf(win.parent) ? win.frameElement : null;
}

// node_modules/@floating-ui/dom/dist/floating-ui.dom.mjs
function getCssDimensions(element) {
  const css = getComputedStyle2(element);
  let width = parseFloat(css.width) || 0;
  let height = parseFloat(css.height) || 0;
  const hasOffset = isHTMLElement(element);
  const offsetWidth = hasOffset ? element.offsetWidth : width;
  const offsetHeight = hasOffset ? element.offsetHeight : height;
  const shouldFallback = round(width) !== offsetWidth || round(height) !== offsetHeight;
  if (shouldFallback) {
    width = offsetWidth;
    height = offsetHeight;
  }
  return {
    width,
    height,
    $: shouldFallback
  };
}
function unwrapElement(element) {
  return !isElement(element) ? element.contextElement : element;
}
function getScale(element) {
  const domElement = unwrapElement(element);
  if (!isHTMLElement(domElement)) {
    return createCoords(1);
  }
  const rect = domElement.getBoundingClientRect();
  const {
    width,
    height,
    $
  } = getCssDimensions(domElement);
  let x = ($ ? round(rect.width) : rect.width) / width;
  let y = ($ ? round(rect.height) : rect.height) / height;
  if (!x || !Number.isFinite(x)) {
    x = 1;
  }
  if (!y || !Number.isFinite(y)) {
    y = 1;
  }
  return {
    x,
    y
  };
}
var noOffsets = /* @__PURE__ */ createCoords(0);
function getVisualOffsets(element) {
  const win = getWindow(element);
  if (!isWebKit() || !win.visualViewport) {
    return noOffsets;
  }
  return {
    x: win.visualViewport.offsetLeft,
    y: win.visualViewport.offsetTop
  };
}
function shouldAddVisualOffsets(element, isFixed, floatingOffsetParent) {
  if (isFixed === void 0) {
    isFixed = false;
  }
  if (!floatingOffsetParent || isFixed && floatingOffsetParent !== getWindow(element)) {
    return false;
  }
  return isFixed;
}
function getBoundingClientRect(element, includeScale, isFixedStrategy, offsetParent) {
  if (includeScale === void 0) {
    includeScale = false;
  }
  if (isFixedStrategy === void 0) {
    isFixedStrategy = false;
  }
  const clientRect = element.getBoundingClientRect();
  const domElement = unwrapElement(element);
  let scale = createCoords(1);
  if (includeScale) {
    if (offsetParent) {
      if (isElement(offsetParent)) {
        scale = getScale(offsetParent);
      }
    } else {
      scale = getScale(element);
    }
  }
  const visualOffsets = shouldAddVisualOffsets(domElement, isFixedStrategy, offsetParent) ? getVisualOffsets(domElement) : createCoords(0);
  let x = (clientRect.left + visualOffsets.x) / scale.x;
  let y = (clientRect.top + visualOffsets.y) / scale.y;
  let width = clientRect.width / scale.x;
  let height = clientRect.height / scale.y;
  if (domElement) {
    const win = getWindow(domElement);
    const offsetWin = offsetParent && isElement(offsetParent) ? getWindow(offsetParent) : offsetParent;
    let currentWin = win;
    let currentIFrame = getFrameElement(currentWin);
    while (currentIFrame && offsetParent && offsetWin !== currentWin) {
      const iframeScale = getScale(currentIFrame);
      const iframeRect = currentIFrame.getBoundingClientRect();
      const css = getComputedStyle2(currentIFrame);
      const left = iframeRect.left + (currentIFrame.clientLeft + parseFloat(css.paddingLeft)) * iframeScale.x;
      const top = iframeRect.top + (currentIFrame.clientTop + parseFloat(css.paddingTop)) * iframeScale.y;
      x *= iframeScale.x;
      y *= iframeScale.y;
      width *= iframeScale.x;
      height *= iframeScale.y;
      x += left;
      y += top;
      currentWin = getWindow(currentIFrame);
      currentIFrame = getFrameElement(currentWin);
    }
  }
  return rectToClientRect({
    width,
    height,
    x,
    y
  });
}
function getWindowScrollBarX(element, rect) {
  const leftScroll = getNodeScroll(element).scrollLeft;
  if (!rect) {
    return getBoundingClientRect(getDocumentElement(element)).left + leftScroll;
  }
  return rect.left + leftScroll;
}
function getHTMLOffset(documentElement, scroll) {
  const htmlRect = documentElement.getBoundingClientRect();
  const x = htmlRect.left + scroll.scrollLeft - getWindowScrollBarX(documentElement, htmlRect);
  const y = htmlRect.top + scroll.scrollTop;
  return {
    x,
    y
  };
}
function convertOffsetParentRelativeRectToViewportRelativeRect(_ref) {
  let {
    elements,
    rect,
    offsetParent,
    strategy
  } = _ref;
  const isFixed = strategy === "fixed";
  const documentElement = getDocumentElement(offsetParent);
  const topLayer = elements ? isTopLayer(elements.floating) : false;
  if (offsetParent === documentElement || topLayer && isFixed) {
    return rect;
  }
  let scroll = {
    scrollLeft: 0,
    scrollTop: 0
  };
  let scale = createCoords(1);
  const offsets = createCoords(0);
  const isOffsetParentAnElement = isHTMLElement(offsetParent);
  if (isOffsetParentAnElement || !isOffsetParentAnElement && !isFixed) {
    if (getNodeName(offsetParent) !== "body" || isOverflowElement(documentElement)) {
      scroll = getNodeScroll(offsetParent);
    }
    if (isOffsetParentAnElement) {
      const offsetRect = getBoundingClientRect(offsetParent);
      scale = getScale(offsetParent);
      offsets.x = offsetRect.x + offsetParent.clientLeft;
      offsets.y = offsetRect.y + offsetParent.clientTop;
    }
  }
  const htmlOffset = documentElement && !isOffsetParentAnElement && !isFixed ? getHTMLOffset(documentElement, scroll) : createCoords(0);
  return {
    width: rect.width * scale.x,
    height: rect.height * scale.y,
    x: rect.x * scale.x - scroll.scrollLeft * scale.x + offsets.x + htmlOffset.x,
    y: rect.y * scale.y - scroll.scrollTop * scale.y + offsets.y + htmlOffset.y
  };
}
function getClientRects(element) {
  return Array.from(element.getClientRects());
}
function getDocumentRect(element) {
  const html = getDocumentElement(element);
  const scroll = getNodeScroll(element);
  const body = element.ownerDocument.body;
  const width = max(html.scrollWidth, html.clientWidth, body.scrollWidth, body.clientWidth);
  const height = max(html.scrollHeight, html.clientHeight, body.scrollHeight, body.clientHeight);
  let x = -scroll.scrollLeft + getWindowScrollBarX(element);
  const y = -scroll.scrollTop;
  if (getComputedStyle2(body).direction === "rtl") {
    x += max(html.clientWidth, body.clientWidth) - width;
  }
  return {
    width,
    height,
    x,
    y
  };
}
var SCROLLBAR_MAX = 25;
function getViewportRect(element, strategy) {
  const win = getWindow(element);
  const html = getDocumentElement(element);
  const visualViewport = win.visualViewport;
  let width = html.clientWidth;
  let height = html.clientHeight;
  let x = 0;
  let y = 0;
  if (visualViewport) {
    width = visualViewport.width;
    height = visualViewport.height;
    const visualViewportBased = isWebKit();
    if (!visualViewportBased || visualViewportBased && strategy === "fixed") {
      x = visualViewport.offsetLeft;
      y = visualViewport.offsetTop;
    }
  }
  const windowScrollbarX = getWindowScrollBarX(html);
  if (windowScrollbarX <= 0) {
    const doc = html.ownerDocument;
    const body = doc.body;
    const bodyStyles = getComputedStyle(body);
    const bodyMarginInline = doc.compatMode === "CSS1Compat" ? parseFloat(bodyStyles.marginLeft) + parseFloat(bodyStyles.marginRight) || 0 : 0;
    const clippingStableScrollbarWidth = Math.abs(html.clientWidth - body.clientWidth - bodyMarginInline);
    if (clippingStableScrollbarWidth <= SCROLLBAR_MAX) {
      width -= clippingStableScrollbarWidth;
    }
  } else if (windowScrollbarX <= SCROLLBAR_MAX) {
    width += windowScrollbarX;
  }
  return {
    width,
    height,
    x,
    y
  };
}
function getInnerBoundingClientRect(element, strategy) {
  const clientRect = getBoundingClientRect(element, true, strategy === "fixed");
  const top = clientRect.top + element.clientTop;
  const left = clientRect.left + element.clientLeft;
  const scale = isHTMLElement(element) ? getScale(element) : createCoords(1);
  const width = element.clientWidth * scale.x;
  const height = element.clientHeight * scale.y;
  const x = left * scale.x;
  const y = top * scale.y;
  return {
    width,
    height,
    x,
    y
  };
}
function getClientRectFromClippingAncestor(element, clippingAncestor, strategy) {
  let rect;
  if (clippingAncestor === "viewport") {
    rect = getViewportRect(element, strategy);
  } else if (clippingAncestor === "document") {
    rect = getDocumentRect(getDocumentElement(element));
  } else if (isElement(clippingAncestor)) {
    rect = getInnerBoundingClientRect(clippingAncestor, strategy);
  } else {
    const visualOffsets = getVisualOffsets(element);
    rect = {
      x: clippingAncestor.x - visualOffsets.x,
      y: clippingAncestor.y - visualOffsets.y,
      width: clippingAncestor.width,
      height: clippingAncestor.height
    };
  }
  return rectToClientRect(rect);
}
function hasFixedPositionAncestor(element, stopNode) {
  const parentNode = getParentNode(element);
  if (parentNode === stopNode || !isElement(parentNode) || isLastTraversableNode(parentNode)) {
    return false;
  }
  return getComputedStyle2(parentNode).position === "fixed" || hasFixedPositionAncestor(parentNode, stopNode);
}
function getClippingElementAncestors(element, cache) {
  const cachedResult = cache.get(element);
  if (cachedResult) {
    return cachedResult;
  }
  let result = getOverflowAncestors(element, [], false).filter((el) => isElement(el) && getNodeName(el) !== "body");
  let currentContainingBlockComputedStyle = null;
  const elementIsFixed = getComputedStyle2(element).position === "fixed";
  let currentNode = elementIsFixed ? getParentNode(element) : element;
  while (isElement(currentNode) && !isLastTraversableNode(currentNode)) {
    const computedStyle = getComputedStyle2(currentNode);
    const currentNodeIsContaining = isContainingBlock(currentNode);
    if (!currentNodeIsContaining && computedStyle.position === "fixed") {
      currentContainingBlockComputedStyle = null;
    }
    const shouldDropCurrentNode = elementIsFixed ? !currentNodeIsContaining && !currentContainingBlockComputedStyle : !currentNodeIsContaining && computedStyle.position === "static" && !!currentContainingBlockComputedStyle && (currentContainingBlockComputedStyle.position === "absolute" || currentContainingBlockComputedStyle.position === "fixed") || isOverflowElement(currentNode) && !currentNodeIsContaining && hasFixedPositionAncestor(element, currentNode);
    if (shouldDropCurrentNode) {
      result = result.filter((ancestor) => ancestor !== currentNode);
    } else {
      currentContainingBlockComputedStyle = computedStyle;
    }
    currentNode = getParentNode(currentNode);
  }
  cache.set(element, result);
  return result;
}
function getClippingRect(_ref) {
  let {
    element,
    boundary,
    rootBoundary,
    strategy
  } = _ref;
  const elementClippingAncestors = boundary === "clippingAncestors" ? isTopLayer(element) ? [] : getClippingElementAncestors(element, this._c) : [].concat(boundary);
  const clippingAncestors = [...elementClippingAncestors, rootBoundary];
  const firstRect = getClientRectFromClippingAncestor(element, clippingAncestors[0], strategy);
  let top = firstRect.top;
  let right = firstRect.right;
  let bottom = firstRect.bottom;
  let left = firstRect.left;
  for (let i = 1; i < clippingAncestors.length; i++) {
    const rect = getClientRectFromClippingAncestor(element, clippingAncestors[i], strategy);
    top = max(rect.top, top);
    right = min(rect.right, right);
    bottom = min(rect.bottom, bottom);
    left = max(rect.left, left);
  }
  return {
    width: right - left,
    height: bottom - top,
    x: left,
    y: top
  };
}
function getDimensions(element) {
  const {
    width,
    height
  } = getCssDimensions(element);
  return {
    width,
    height
  };
}
function getRectRelativeToOffsetParent(element, offsetParent, strategy) {
  const isOffsetParentAnElement = isHTMLElement(offsetParent);
  const documentElement = getDocumentElement(offsetParent);
  const isFixed = strategy === "fixed";
  const rect = getBoundingClientRect(element, true, isFixed, offsetParent);
  let scroll = {
    scrollLeft: 0,
    scrollTop: 0
  };
  const offsets = createCoords(0);
  function setLeftRTLScrollbarOffset() {
    offsets.x = getWindowScrollBarX(documentElement);
  }
  if (isOffsetParentAnElement || !isOffsetParentAnElement && !isFixed) {
    if (getNodeName(offsetParent) !== "body" || isOverflowElement(documentElement)) {
      scroll = getNodeScroll(offsetParent);
    }
    if (isOffsetParentAnElement) {
      const offsetRect = getBoundingClientRect(offsetParent, true, isFixed, offsetParent);
      offsets.x = offsetRect.x + offsetParent.clientLeft;
      offsets.y = offsetRect.y + offsetParent.clientTop;
    } else if (documentElement) {
      setLeftRTLScrollbarOffset();
    }
  }
  if (isFixed && !isOffsetParentAnElement && documentElement) {
    setLeftRTLScrollbarOffset();
  }
  const htmlOffset = documentElement && !isOffsetParentAnElement && !isFixed ? getHTMLOffset(documentElement, scroll) : createCoords(0);
  const x = rect.left + scroll.scrollLeft - offsets.x - htmlOffset.x;
  const y = rect.top + scroll.scrollTop - offsets.y - htmlOffset.y;
  return {
    x,
    y,
    width: rect.width,
    height: rect.height
  };
}
function isStaticPositioned(element) {
  return getComputedStyle2(element).position === "static";
}
function getTrueOffsetParent(element, polyfill) {
  if (!isHTMLElement(element) || getComputedStyle2(element).position === "fixed") {
    return null;
  }
  if (polyfill) {
    return polyfill(element);
  }
  let rawOffsetParent = element.offsetParent;
  if (getDocumentElement(element) === rawOffsetParent) {
    rawOffsetParent = rawOffsetParent.ownerDocument.body;
  }
  return rawOffsetParent;
}
function getOffsetParent(element, polyfill) {
  const win = getWindow(element);
  if (isTopLayer(element)) {
    return win;
  }
  if (!isHTMLElement(element)) {
    let svgOffsetParent = getParentNode(element);
    while (svgOffsetParent && !isLastTraversableNode(svgOffsetParent)) {
      if (isElement(svgOffsetParent) && !isStaticPositioned(svgOffsetParent)) {
        return svgOffsetParent;
      }
      svgOffsetParent = getParentNode(svgOffsetParent);
    }
    return win;
  }
  let offsetParent = getTrueOffsetParent(element, polyfill);
  while (offsetParent && isTableElement(offsetParent) && isStaticPositioned(offsetParent)) {
    offsetParent = getTrueOffsetParent(offsetParent, polyfill);
  }
  if (offsetParent && isLastTraversableNode(offsetParent) && isStaticPositioned(offsetParent) && !isContainingBlock(offsetParent)) {
    return win;
  }
  return offsetParent || getContainingBlock(element) || win;
}
var getElementRects = async function(data) {
  const getOffsetParentFn = this.getOffsetParent || getOffsetParent;
  const getDimensionsFn = this.getDimensions;
  const floatingDimensions = await getDimensionsFn(data.floating);
  return {
    reference: getRectRelativeToOffsetParent(data.reference, await getOffsetParentFn(data.floating), data.strategy),
    floating: {
      x: 0,
      y: 0,
      width: floatingDimensions.width,
      height: floatingDimensions.height
    }
  };
};
function isRTL(element) {
  return getComputedStyle2(element).direction === "rtl";
}
var platform = {
  convertOffsetParentRelativeRectToViewportRelativeRect,
  getDocumentElement,
  getClippingRect,
  getOffsetParent,
  getElementRects,
  getClientRects,
  getDimensions,
  getScale,
  isElement,
  isRTL
};
var offset2 = offset;
var shift2 = shift;
var flip2 = flip;
var size2 = size;
var computePosition2 = (reference, floating, options) => {
  const cache = /* @__PURE__ */ new Map();
  const mergedOptions = {
    platform,
    ...options
  };
  const platformWithCache = {
    ...mergedOptions.platform,
    _c: cache
  };
  return computePosition(reference, floating, {
    ...mergedOptions,
    platform: platformWithCache
  });
};

// src/context-menu.ts
function dismissAllMenus() {
  const menus = document.querySelectorAll("[data-sm-menu]");
  Array.from(menus).forEach((el) => {
    const smEl = el;
    clearTimeouts(smEl);
    const markDismissed = smEl._smDismissed;
    if (markDismissed)
      markDismissed();
    const cleanup = smEl._smCleanup;
    if (cleanup)
      cleanup();
    smEl.remove();
  });
}
function clearTimeouts(el) {
  const groups = el.querySelectorAll("[data-sm-timeouts]");
  Array.from(groups).forEach((g) => {
    const ids = g.dataset.smTimeouts;
    if (ids) {
      ids.split(",").forEach((id) => {
        const n = parseInt(id, 10);
        if (!isNaN(n))
          clearTimeout(n);
      });
    }
  });
}
function showContextMenu(ev, profile, app) {
  dismissAllMenus();
  const bodyZoom = parseFloat(document.body.style.zoom) || 1;
  const x = ev.clientX / bodyZoom;
  const y = ev.clientY / bodyZoom;
  const menuEl = buildMenu(profile, app);
  menuEl.setAttribute("data-sm-menu", "");
  document.body.appendChild(menuEl);
  let dismissed = false;
  menuEl._smDismissed = () => dismissed = true;
  const virtualEl = {
    getBoundingClientRect: () => DOMRect.fromRect({ x, y, width: 0, height: 0 })
  };
  computePosition2(virtualEl, menuEl, {
    placement: "bottom-start",
    middleware: [
      offset2(4),
      flip2({ padding: 10 }),
      shift2({ padding: 10 }),
      size2({
        apply({ availableHeight, elements }) {
          elements.floating.style.maxHeight = `${Math.max(Math.min(availableHeight - 16, 600), 100)}px`;
          elements.floating.style.overflowY = "auto";
        },
        padding: 8
      })
    ]
  }).then(({ x: fx, y: fy }) => {
    if (dismissed)
      return;
    menuEl.style.left = `${Math.floor(fx)}px`;
    menuEl.style.top = `${Math.floor(fy)}px`;
  });
  const cleanup = registerDismissHandlers(menuEl);
  menuEl._smCleanup = cleanup;
}
function buildMenu(profile, app) {
  const menu = document.createElement("div");
  menu.className = "sm-menu";
  const validMain = profile.mainMenuCommands.filter((e) => e.commandId || e.isSeparator);
  const validSubmenus = profile.submenus.filter(
    (s) => s.entries.some((e) => e.commandId || e.isSeparator)
  );
  if (validMain.length === 0 && validSubmenus.length === 0) {
    const empty = menu.createDiv({ cls: "sm-menu-empty", text: "No commands configured" });
    empty.style.cssText = "padding: 12px 16px; color: var(--text-muted); font-size: 12px; text-align: center;";
    return menu;
  }
  for (const cmd of validMain) {
    menu.appendChild(createItem(cmd, app));
  }
  for (const section of validSubmenus) {
    const valid = section.entries.filter((e) => e.commandId || e.isSeparator);
    menu.appendChild(createGroup(section, valid, app));
  }
  return menu;
}
function createItem(entry, app) {
  if (entry.isSeparator)
    return createSeparator();
  const item = document.createElement("div");
  item.className = "sm-menu-item";
  if (entry.color) {
    item.style.color = entry.color;
  }
  if (entry.icon) {
    const iconEl = item.createSpan({ cls: "sm-menu-item-icon" });
    if (entry.color) {
      iconEl.style.color = entry.color;
    }
    try {
      (0, import_obsidian3.setIcon)(iconEl, entry.icon);
    } catch (e) {
    }
  }
  const label = item.createSpan({ cls: "sm-menu-item-label", text: entry.label });
  item.addEventListener("click", (e) => {
    e.stopPropagation();
    dismissAllMenus();
    app.commands.executeCommandById(entry.commandId);
  });
  return item;
}
function createGroup(section, entries, app) {
  const group = document.createElement("div");
  group.className = "sm-menu-group";
  const trigger = document.createElement("div");
  trigger.className = "sm-menu-item sm-group-trigger";
  if (section.color)
    trigger.style.color = section.color;
  if (section.icon) {
    const iconEl = trigger.createSpan({ cls: "sm-menu-item-icon" });
    if (section.color)
      iconEl.style.color = section.color;
    try {
      (0, import_obsidian3.setIcon)(iconEl, section.icon);
    } catch (e) {
    }
  }
  trigger.createSpan({ cls: "sm-menu-item-label", text: section.label });
  const arrow2 = trigger.createSpan({ cls: "sm-group-arrow" });
  (0, import_obsidian3.setIcon)(arrow2, "chevron-right");
  const submenu = document.createElement("div");
  submenu.className = "sm-submenu";
  submenu.setAttribute("data-sm-menu", "");
  submenu.style.position = "fixed";
  submenu.style.zIndex = "calc(var(--layer-menu) + 2)";
  for (const entry of entries) {
    submenu.appendChild(createItem(entry, app));
  }
  submenu.addEventListener("click", (e) => e.stopPropagation());
  group.appendChild(trigger);
  let hideTimeout = null;
  let showTimeout = null;
  const saveTimeouts = () => {
    const ids = [];
    if (showTimeout !== null)
      ids.push(showTimeout);
    if (hideTimeout !== null)
      ids.push(hideTimeout);
    group.dataset.smTimeouts = ids.join(",");
  };
  const positionAndShow = () => {
    document.body.appendChild(submenu);
    computePosition2(trigger, submenu, {
      placement: "right-start",
      middleware: [
        offset2(4),
        flip2({ padding: 10 }),
        shift2({ padding: 10 }),
        size2({
          apply({ availableHeight }) {
            submenu.style.maxHeight = `${Math.max(Math.min(availableHeight - 16, 600), 100)}px`;
            submenu.style.overflowY = "auto";
          },
          padding: 8
        })
      ]
    }).then(({ x, y }) => {
      submenu.style.left = `${Math.floor(x)}px`;
      submenu.style.top = `${Math.floor(y)}px`;
      submenu.classList.add("sm-submenu-visible");
    });
  };
  const show = () => {
    if (hideTimeout !== null)
      clearTimeout(hideTimeout);
    if (showTimeout !== null)
      clearTimeout(showTimeout);
    showTimeout = window.setTimeout(() => {
      positionAndShow();
      showTimeout = null;
      saveTimeouts();
    }, 150);
    saveTimeouts();
  };
  const hide2 = () => {
    if (showTimeout !== null)
      clearTimeout(showTimeout);
    if (hideTimeout !== null)
      clearTimeout(hideTimeout);
    hideTimeout = window.setTimeout(() => {
      submenu.classList.remove("sm-submenu-visible");
      if (submenu.parentElement)
        submenu.remove();
      hideTimeout = null;
      saveTimeouts();
    }, 200);
    saveTimeouts();
  };
  trigger.addEventListener("mouseenter", show);
  trigger.addEventListener("mouseleave", (e) => {
    const related = e.relatedTarget;
    if (!related || !submenu.contains(related))
      hide2();
  });
  submenu.addEventListener("mouseenter", () => {
    if (hideTimeout !== null)
      clearTimeout(hideTimeout);
    hideTimeout = null;
    submenu.classList.add("sm-submenu-visible");
    saveTimeouts();
  });
  submenu.addEventListener("mouseleave", (e) => {
    const related = e.relatedTarget;
    if (!related || !group.contains(related))
      hide2();
  });
  return group;
}
function createSeparator() {
  const sep = document.createElement("div");
  sep.className = "sm-menu-separator";
  return sep;
}
function registerDismissHandlers(menuEl) {
  const onKeyDown = (e) => {
    if (e.key === "Escape")
      dismissAllMenus();
  };
  const onClick = (e) => {
    if (!menuEl.contains(e.target))
      dismissAllMenus();
  };
  document.addEventListener("keydown", onKeyDown, true);
  document.addEventListener("click", onClick, true);
  return () => {
    document.removeEventListener("keydown", onKeyDown, true);
    document.removeEventListener("click", onClick, true);
  };
}

// src/main.ts
var ScriptMenusPlugin = class extends import_obsidian4.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new ScriptMenusSettingTab(this.app, this));
    this.registerDomEvent(document, "contextmenu", (ev) => {
      dismissAllMenus();
      const view = this.app.workspace.getActiveViewOfType(import_obsidian4.MarkdownView);
      if (!view)
        return;
      if (view.getMode() !== "source")
        return;
      try {
        for (const profile of this.settings.profiles) {
          if (ev.altKey === profile.modifiers.alt && ev.ctrlKey === profile.modifiers.ctrl && ev.shiftKey === profile.modifiers.shift && ev.metaKey === profile.modifiers.meta) {
            ev.preventDefault();
            ev.stopPropagation();
            showContextMenu(ev, profile, this.app);
            return;
          }
        }
      } catch (e) {
      }
    }, true);
  }
  onunload() {
    dismissAllMenus();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    for (const profile of this.settings.profiles) {
      if (profile.submenus && !Array.isArray(profile.submenus)) {
        const old = profile.submenus;
        profile.submenus = Object.entries(old).map(([label, entries]) => ({
          label,
          entries: entries || []
        }));
      }
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
