/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ScriptMenusPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/settings.ts
var import_obsidian2 = require("obsidian");

// src/modal.ts
var import_obsidian = require("obsidian");
var CommandSuggestModal = class extends import_obsidian.FuzzySuggestModal {
  constructor(app, onSelect) {
    super(app);
    this.onSelect = onSelect;
    this.setPlaceholder("Type to search for a command...");
    this.setInstructions([
      { command: "\u2191\u2193", purpose: "Navigate" },
      { command: "\u21B5", purpose: "Select command" },
      { command: "esc", purpose: "Close" }
    ]);
  }
  getItems() {
    return this.app.commands.listCommands();
  }
  getItemText(command) {
    return command.name;
  }
  onChooseItem(command) {
    this.onSelect(command);
  }
};
var IconInputModal = class extends import_obsidian.Modal {
  constructor(app, currentIcon, onSelect) {
    super(app);
    this.currentIcon = currentIcon;
    this.onSelect = onSelect;
    this.setTitle("Choose icon");
  }
  onOpen() {
    const { contentEl } = this;
    const desc = contentEl.createEl("p", {
      text: "Enter a Lucide icon name (e.g. 'star', 'trash-2', 'settings')."
    });
    desc.style.cssText = "font-size: 12px; color: var(--text-muted); margin-bottom: 12px;";
    const previewRow = contentEl.createDiv();
    previewRow.style.cssText = "display: flex; align-items: center; gap: 12px; margin-bottom: 12px;";
    const previewIcon = previewRow.createSpan();
    previewIcon.style.cssText = "width: 24px; height: 24px; display: flex; align-items: center; justify-content: center;";
    const previewLabel = previewRow.createSpan();
    previewLabel.style.cssText = "font-size: 13px; color: var(--text-muted);";
    const input = contentEl.createEl("input", { type: "text" });
    input.value = this.currentIcon;
    input.placeholder = "e.g. star, trash-2, settings";
    input.style.cssText = "width: 100%; background: var(--background-primary); margin-bottom: 16px;";
    const updatePreview = () => {
      previewIcon.empty();
      previewLabel.setText("");
      if (input.value.trim()) {
        try {
          (0, import_obsidian.setIcon)(previewIcon, input.value.trim());
          previewLabel.setText(input.value.trim());
        } catch (e) {
          previewLabel.setText(`"${input.value.trim()}" not found`);
        }
      }
    };
    updatePreview();
    input.addEventListener("input", updatePreview);
    const btnRow = contentEl.createDiv();
    btnRow.style.cssText = "display: flex; justify-content: flex-end; gap: 8px;";
    const clearBtn = btnRow.createEl("button", { text: "Clear" });
    clearBtn.onclick = () => {
      this.onSelect("");
      this.close();
    };
    const applyBtn = btnRow.createEl("button", { text: "Apply", cls: "mod-cta" });
    applyBtn.onclick = () => {
      this.onSelect(input.value.trim());
      this.close();
    };
    input.addEventListener("keydown", (e) => {
      if (e.key === "Enter")
        applyBtn.click();
    });
    setTimeout(() => input.focus(), 100);
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/settings.ts
var DEFAULT_SETTINGS = {
  profiles: [
    {
      name: "Main",
      modifiers: { alt: true, ctrl: false, shift: false, meta: false },
      submenus: {},
      mainMenuCommands: []
    }
  ]
};
var ScriptMenusSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Script Menus Settings" });
    containerEl.createEl("p", {
      text: "Right-click with a modifier key in the editor to open a custom menu with your commands. If no modifier matches, the default Obsidian context menu appears.",
      cls: "setting-item-description"
    });
    this.renderProfiles();
  }
  renderProfiles() {
    const { containerEl } = this;
    const profiles = this.plugin.settings.profiles;
    containerEl.createEl("h3", { text: "Menu Profiles" });
    const profilesContainer = containerEl.createDiv();
    profilesContainer.style.marginBottom = "16px";
    for (let i = 0; i < profiles.length; i++) {
      this.renderProfileCard(profilesContainer, i);
    }
    if (profiles.length < 8) {
      const addRow = containerEl.createDiv();
      addRow.style.marginTop = "8px";
      const addBtn = addRow.createEl("button", { text: "+ Add profile" });
      addBtn.onclick = async () => {
        const usedModifiers = new Set(
          profiles.map((p) => `${p.modifiers.alt}/${p.modifiers.ctrl}/${p.modifiers.shift}/${p.modifiers.meta}`)
        );
        let combo = { alt: false, ctrl: false, shift: false, meta: false };
        for (const m of ["shift", "ctrl", "alt", "meta"]) {
          const test = { alt: false, ctrl: false, shift: false, meta: false };
          test[m] = true;
          if (!usedModifiers.has(`${test.alt}/${test.ctrl}/${test.shift}/${test.meta}`)) {
            combo = test;
            break;
          }
        }
        this.plugin.settings.profiles = [
          ...this.plugin.settings.profiles,
          { name: `Profile ${profiles.length + 1}`, modifiers: combo, submenus: {}, mainMenuCommands: [] }
        ];
        await this.plugin.saveSettings();
        this.display();
      };
    }
  }
  renderProfileCard(container, index) {
    const profile = this.plugin.settings.profiles[index];
    const card = container.createDiv();
    card.style.cssText = `
      border: 1px solid var(--background-modifier-border);
      border-radius: 6px;
      padding: 12px;
      margin-bottom: 12px;
    `;
    const header = card.createDiv();
    header.style.cssText = "display: flex; align-items: center; gap: 8px; margin-bottom: 12px;";
    const nameInput = header.createEl("input", { type: "text", value: profile.name });
    nameInput.style.cssText = "flex: 1; font-weight: bold; background: var(--background-primary);";
    nameInput.placeholder = "Profile name";
    nameInput.onchange = async () => {
      this.plugin.settings.profiles[index].name = nameInput.value;
      await this.plugin.saveSettings();
    };
    if (this.plugin.settings.profiles.length > 1) {
      const removeBtn = header.createEl("button", { text: "\xD7 Remove" });
      removeBtn.style.cssText = "background: transparent; border: none; cursor: pointer; color: var(--text-muted); font-size: 12px;";
      removeBtn.onclick = async () => {
        this.plugin.settings.profiles = [
          ...this.plugin.settings.profiles.slice(0, index),
          ...this.plugin.settings.profiles.slice(index + 1)
        ];
        await this.plugin.saveSettings();
        this.display();
      };
    }
    const modLabel = card.createEl("span", { text: "Modifier combination:" });
    modLabel.style.cssText = "font-size: 12px; color: var(--text-muted); margin-bottom: 6px; display: block;";
    const modRow = card.createDiv();
    modRow.style.cssText = "display: flex; gap: 16px; margin-bottom: 16px;";
    const renderModCheckbox = (label, key) => {
      const labelEl = modRow.createEl("label");
      labelEl.style.cssText = "display: flex; align-items: center; gap: 4px; cursor: pointer; font-size: 13px;";
      const cb = labelEl.createEl("input", { type: "checkbox" });
      cb.checked = profile.modifiers[key];
      cb.onchange = async () => {
        this.plugin.settings.profiles[index].modifiers[key] = cb.checked;
        await this.plugin.saveSettings();
      };
      labelEl.append(` ${label}`);
    };
    renderModCheckbox("Alt", "alt");
    renderModCheckbox("Ctrl", "ctrl");
    renderModCheckbox("Shift", "shift");
    renderModCheckbox("Meta", "meta");
    this.renderSubmenus(card, index);
    this.renderMainCommands(card, index);
  }
  renderSubmenus(container, profileIndex) {
    const profile = this.plugin.settings.profiles[profileIndex];
    container.createEl("h4", { text: "Submenus" });
    const desc = container.createEl("p", {
      text: "Named groups shown as submenus in the menu.",
      cls: "setting-item-description"
    });
    const sectionContainer = container.createDiv();
    sectionContainer.style.marginBottom = "8px";
    const renderSubmenuSections = () => {
      const existing = sectionContainer.querySelectorAll(".sm-submenu-section");
      Array.from(existing).forEach((el) => el.remove());
      for (const [sectionName, entries] of Object.entries(profile.submenus)) {
        const sectionDiv = sectionContainer.createDiv();
        sectionDiv.className = "sm-submenu-section";
        sectionDiv.style.cssText = "margin-bottom: 8px; border: 1px solid var(--background-modifier-border); border-radius: 4px; padding: 8px;";
        const headerRow = sectionDiv.createDiv();
        headerRow.style.cssText = "display: flex; gap: 8px; align-items: center; margin-bottom: 8px;";
        const title = headerRow.createEl("span", { text: sectionName });
        title.style.cssText = "font-weight: bold; flex: 1;";
        const removeBtn = headerRow.createEl("button", { text: "\xD7 Remove section" });
        removeBtn.style.cssText = "background: transparent; border: none; cursor: pointer; color: var(--text-muted); font-size: 12px;";
        removeBtn.onclick = async () => {
          const next = { ...this.plugin.settings.profiles[profileIndex].submenus };
          delete next[sectionName];
          this.plugin.settings.profiles[profileIndex].submenus = next;
          await this.plugin.saveSettings();
          renderSubmenuSections();
        };
        const entriesDiv = sectionDiv.createDiv();
        for (let i = 0; i < entries.length; i++) {
          this.renderEntryRow(entriesDiv, entries, i, () => this.plugin.settings.profiles[profileIndex].submenus[sectionName], renderSubmenuSections);
        }
        const addCmdRow = sectionDiv.createDiv();
        addCmdRow.style.marginTop = "4px";
        const addCmdBtn = addCmdRow.createEl("button", { text: "+ Add command" });
        addCmdBtn.onclick = async () => {
          entries.push({ label: "New command", commandId: "" });
          this.plugin.settings.profiles[profileIndex].submenus = { ...this.plugin.settings.profiles[profileIndex].submenus };
          await this.plugin.saveSettings();
          renderSubmenuSections();
        };
      }
    };
    const addSectionRow = sectionContainer.createDiv();
    addSectionRow.style.cssText = "display: flex; gap: 8px; align-items: center; margin-bottom: 12px;";
    const sectionNameInput = addSectionRow.createEl("input", { type: "text" });
    sectionNameInput.placeholder = "Section name (e.g. Utils, Format...)";
    sectionNameInput.style.cssText = "flex: 1; background: var(--background-primary);";
    const addBtn = addSectionRow.createEl("button", { text: "+ Add section" });
    addBtn.onclick = async () => {
      const name = sectionNameInput.value.trim();
      if (!name)
        return;
      if (profile.submenus[name])
        return;
      this.plugin.settings.profiles[profileIndex].submenus = {
        ...this.plugin.settings.profiles[profileIndex].submenus,
        [name]: []
      };
      await this.plugin.saveSettings();
      sectionNameInput.value = "";
      renderSubmenuSections();
    };
    renderSubmenuSections();
  }
  renderMainCommands(container, profileIndex) {
    const profile = this.plugin.settings.profiles[profileIndex];
    container.createEl("h4", { text: "Main commands" });
    container.createEl("p", {
      text: "Commands shown at the top of the menu, outside any submenu.",
      cls: "setting-item-description"
    });
    const cmdContainer = container.createDiv();
    cmdContainer.style.marginBottom = "8px";
    const render = () => {
      cmdContainer.empty();
      const list = this.plugin.settings.profiles[profileIndex].mainMenuCommands;
      for (let i = 0; i < list.length; i++) {
        this.renderEntryRow(cmdContainer, list, i, () => this.plugin.settings.profiles[profileIndex].mainMenuCommands, render);
      }
      const addRow = cmdContainer.createDiv();
      addRow.style.marginTop = "8px";
      const addBtn = addRow.createEl("button", { text: "+ Add command" });
      addBtn.onclick = async () => {
        this.plugin.settings.profiles[profileIndex].mainMenuCommands = [
          ...this.plugin.settings.profiles[profileIndex].mainMenuCommands,
          { label: "New command", commandId: "" }
        ];
        await this.plugin.saveSettings();
        render();
      };
    };
    render();
  }
  renderEntryRow(container, list, index, getList, onRemove) {
    const row = container.createDiv();
    row.style.cssText = "display: flex; gap: 8px; align-items: center; margin-bottom: 4px;";
    const labelInput = row.createEl("input", { type: "text" });
    labelInput.value = list[index].label;
    labelInput.style.cssText = "flex: 1; background: var(--background-primary);";
    labelInput.placeholder = "Label (e.g. My script)";
    const iconBtn = row.createEl("button");
    iconBtn.style.cssText = "width: 28px; height: 28px; display: flex; align-items: center; justify-content: center; background: transparent; border: 1px solid var(--background-modifier-border); border-radius: 4px; cursor: pointer; color: var(--text-muted); flex-shrink: 0;";
    iconBtn.title = "Choose icon";
    const renderIcon = () => {
      iconBtn.empty();
      if (list[index].icon) {
        (0, import_obsidian2.setIcon)(iconBtn, list[index].icon);
      } else {
        iconBtn.setText("?");
      }
    };
    renderIcon();
    iconBtn.onclick = () => {
      new IconInputModal(this.app, list[index].icon || "", (iconName) => {
        list[index].icon = iconName || void 0;
        getList();
        renderIcon();
        this.plugin.saveSettings();
      }).open();
    };
    const cmdInput = row.createEl("input", { type: "text" });
    cmdInput.value = list[index].commandId;
    cmdInput.style.cssText = "flex: 1; background: var(--background-primary);";
    cmdInput.placeholder = "Command ID (e.g. my-plugin:action)";
    const searchBtn = row.createEl("button", { text: "Find..." });
    searchBtn.style.cssText = "background: transparent; border: none; cursor: pointer; color: var(--text-muted); font-size: 12px;";
    searchBtn.title = "Search for a command";
    searchBtn.onclick = () => {
      new CommandSuggestModal(this.app, (command) => {
        labelInput.value = command.name;
        cmdInput.value = command.id;
        list[index].label = command.name;
        list[index].commandId = command.id;
        this.plugin.saveSettings();
      }).open();
    };
    const removeBtn = row.createEl("button", { text: "\xD7" });
    removeBtn.style.cssText = "background: transparent; border: none; cursor: pointer; color: var(--text-muted);";
    removeBtn.onclick = async () => {
      const updated = [...list.slice(0, index), ...list.slice(index + 1)];
      for (let j = 0; j < updated.length; j++)
        list[j] = updated[j];
      list.length = updated.length;
      await this.plugin.saveSettings();
      if (onRemove)
        onRemove();
    };
    labelInput.onchange = async () => {
      list[index].label = labelInput.value;
      await this.plugin.saveSettings();
    };
    cmdInput.onchange = async () => {
      list[index].commandId = cmdInput.value;
      await this.plugin.saveSettings();
    };
  }
};

// src/context-menu.ts
var import_obsidian3 = require("obsidian");

// node_modules/@floating-ui/utils/dist/floating-ui.utils.mjs
var min = Math.min;
var max = Math.max;
var round = Math.round;
var createCoords = (v) => ({
  x: v,
  y: v
});
var oppositeSideMap = {
  left: "right",
  right: "left",
  bottom: "top",
  top: "bottom"
};
function clamp(start, value, end) {
  return max(start, min(value, end));
}
function evaluate(value, param) {
  return typeof value === "function" ? value(param) : value;
}
function getSide(placement) {
  return placement.split("-")[0];
}
function getAlignment(placement) {
  return placement.split("-")[1];
}
function getOppositeAxis(axis) {
  return axis === "x" ? "y" : "x";
}
function getAxisLength(axis) {
  return axis === "y" ? "height" : "width";
}
function getSideAxis(placement) {
  const firstChar = placement[0];
  return firstChar === "t" || firstChar === "b" ? "y" : "x";
}
function getAlignmentAxis(placement) {
  return getOppositeAxis(getSideAxis(placement));
}
function getAlignmentSides(placement, rects, rtl) {
  if (rtl === void 0) {
    rtl = false;
  }
  const alignment = getAlignment(placement);
  const alignmentAxis = getAlignmentAxis(placement);
  const length = getAxisLength(alignmentAxis);
  let mainAlignmentSide = alignmentAxis === "x" ? alignment === (rtl ? "end" : "start") ? "right" : "left" : alignment === "start" ? "bottom" : "top";
  if (rects.reference[length] > rects.floating[length]) {
    mainAlignmentSide = getOppositePlacement(mainAlignmentSide);
  }
  return [mainAlignmentSide, getOppositePlacement(mainAlignmentSide)];
}
function getExpandedPlacements(placement) {
  const oppositePlacement = getOppositePlacement(placement);
  return [getOppositeAlignmentPlacement(placement), oppositePlacement, getOppositeAlignmentPlacement(oppositePlacement)];
}
function getOppositeAlignmentPlacement(placement) {
  return placement.includes("start") ? placement.replace("start", "end") : placement.replace("end", "start");
}
var lrPlacement = ["left", "right"];
var rlPlacement = ["right", "left"];
var tbPlacement = ["top", "bottom"];
var btPlacement = ["bottom", "top"];
function getSideList(side, isStart, rtl) {
  switch (side) {
    case "top":
    case "bottom":
      if (rtl)
        return isStart ? rlPlacement : lrPlacement;
      return isStart ? lrPlacement : rlPlacement;
    case "left":
    case "right":
      return isStart ? tbPlacement : btPlacement;
    default:
      return [];
  }
}
function getOppositeAxisPlacements(placement, flipAlignment, direction, rtl) {
  const alignment = getAlignment(placement);
  let list = getSideList(getSide(placement), direction === "start", rtl);
  if (alignment) {
    list = list.map((side) => side + "-" + alignment);
    if (flipAlignment) {
      list = list.concat(list.map(getOppositeAlignmentPlacement));
    }
  }
  return list;
}
function getOppositePlacement(placement) {
  const side = getSide(placement);
  return oppositeSideMap[side] + placement.slice(side.length);
}
function expandPaddingObject(padding) {
  return {
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    ...padding
  };
}
function getPaddingObject(padding) {
  return typeof padding !== "number" ? expandPaddingObject(padding) : {
    top: padding,
    right: padding,
    bottom: padding,
    left: padding
  };
}
function rectToClientRect(rect) {
  const {
    x,
    y,
    width,
    height
  } = rect;
  return {
    width,
    height,
    top: y,
    left: x,
    right: x + width,
    bottom: y + height,
    x,
    y
  };
}

// node_modules/@floating-ui/core/dist/floating-ui.core.mjs
function computeCoordsFromPlacement(_ref, placement, rtl) {
  let {
    reference,
    floating
  } = _ref;
  const sideAxis = getSideAxis(placement);
  const alignmentAxis = getAlignmentAxis(placement);
  const alignLength = getAxisLength(alignmentAxis);
  const side = getSide(placement);
  const isVertical = sideAxis === "y";
  const commonX = reference.x + reference.width / 2 - floating.width / 2;
  const commonY = reference.y + reference.height / 2 - floating.height / 2;
  const commonAlign = reference[alignLength] / 2 - floating[alignLength] / 2;
  let coords;
  switch (side) {
    case "top":
      coords = {
        x: commonX,
        y: reference.y - floating.height
      };
      break;
    case "bottom":
      coords = {
        x: commonX,
        y: reference.y + reference.height
      };
      break;
    case "right":
      coords = {
        x: reference.x + reference.width,
        y: commonY
      };
      break;
    case "left":
      coords = {
        x: reference.x - floating.width,
        y: commonY
      };
      break;
    default:
      coords = {
        x: reference.x,
        y: reference.y
      };
  }
  switch (getAlignment(placement)) {
    case "start":
      coords[alignmentAxis] -= commonAlign * (rtl && isVertical ? -1 : 1);
      break;
    case "end":
      coords[alignmentAxis] += commonAlign * (rtl && isVertical ? -1 : 1);
      break;
  }
  return coords;
}
async function detectOverflow(state, options) {
  var _await$platform$isEle;
  if (options === void 0) {
    options = {};
  }
  const {
    x,
    y,
    platform: platform2,
    rects,
    elements,
    strategy
  } = state;
  const {
    boundary = "clippingAncestors",
    rootBoundary = "viewport",
    elementContext = "floating",
    altBoundary = false,
    padding = 0
  } = evaluate(options, state);
  const paddingObject = getPaddingObject(padding);
  const altContext = elementContext === "floating" ? "reference" : "floating";
  const element = elements[altBoundary ? altContext : elementContext];
  const clippingClientRect = rectToClientRect(await platform2.getClippingRect({
    element: ((_await$platform$isEle = await (platform2.isElement == null ? void 0 : platform2.isElement(element))) != null ? _await$platform$isEle : true) ? element : element.contextElement || await (platform2.getDocumentElement == null ? void 0 : platform2.getDocumentElement(elements.floating)),
    boundary,
    rootBoundary,
    strategy
  }));
  const rect = elementContext === "floating" ? {
    x,
    y,
    width: rects.floating.width,
    height: rects.floating.height
  } : rects.reference;
  const offsetParent = await (platform2.getOffsetParent == null ? void 0 : platform2.getOffsetParent(elements.floating));
  const offsetScale = await (platform2.isElement == null ? void 0 : platform2.isElement(offsetParent)) ? await (platform2.getScale == null ? void 0 : platform2.getScale(offsetParent)) || {
    x: 1,
    y: 1
  } : {
    x: 1,
    y: 1
  };
  const elementClientRect = rectToClientRect(platform2.convertOffsetParentRelativeRectToViewportRelativeRect ? await platform2.convertOffsetParentRelativeRectToViewportRelativeRect({
    elements,
    rect,
    offsetParent,
    strategy
  }) : rect);
  return {
    top: (clippingClientRect.top - elementClientRect.top + paddingObject.top) / offsetScale.y,
    bottom: (elementClientRect.bottom - clippingClientRect.bottom + paddingObject.bottom) / offsetScale.y,
    left: (clippingClientRect.left - elementClientRect.left + paddingObject.left) / offsetScale.x,
    right: (elementClientRect.right - clippingClientRect.right + paddingObject.right) / offsetScale.x
  };
}
var MAX_RESET_COUNT = 50;
var computePosition = async (reference, floating, config) => {
  const {
    placement = "bottom",
    strategy = "absolute",
    middleware = [],
    platform: platform2
  } = config;
  const platformWithDetectOverflow = platform2.detectOverflow ? platform2 : {
    ...platform2,
    detectOverflow
  };
  const rtl = await (platform2.isRTL == null ? void 0 : platform2.isRTL(floating));
  let rects = await platform2.getElementRects({
    reference,
    floating,
    strategy
  });
  let {
    x,
    y
  } = computeCoordsFromPlacement(rects, placement, rtl);
  let statefulPlacement = placement;
  let resetCount = 0;
  const middlewareData = {};
  for (let i = 0; i < middleware.length; i++) {
    const currentMiddleware = middleware[i];
    if (!currentMiddleware) {
      continue;
    }
    const {
      name,
      fn
    } = currentMiddleware;
    const {
      x: nextX,
      y: nextY,
      data,
      reset
    } = await fn({
      x,
      y,
      initialPlacement: placement,
      placement: statefulPlacement,
      strategy,
      middlewareData,
      rects,
      platform: platformWithDetectOverflow,
      elements: {
        reference,
        floating
      }
    });
    x = nextX != null ? nextX : x;
    y = nextY != null ? nextY : y;
    middlewareData[name] = {
      ...middlewareData[name],
      ...data
    };
    if (reset && resetCount < MAX_RESET_COUNT) {
      resetCount++;
      if (typeof reset === "object") {
        if (reset.placement) {
          statefulPlacement = reset.placement;
        }
        if (reset.rects) {
          rects = reset.rects === true ? await platform2.getElementRects({
            reference,
            floating,
            strategy
          }) : reset.rects;
        }
        ({
          x,
          y
        } = computeCoordsFromPlacement(rects, statefulPlacement, rtl));
      }
      i = -1;
    }
  }
  return {
    x,
    y,
    placement: statefulPlacement,
    strategy,
    middlewareData
  };
};
var flip = function(options) {
  if (options === void 0) {
    options = {};
  }
  return {
    name: "flip",
    options,
    async fn(state) {
      var _middlewareData$arrow, _middlewareData$flip;
      const {
        placement,
        middlewareData,
        rects,
        initialPlacement,
        platform: platform2,
        elements
      } = state;
      const {
        mainAxis: checkMainAxis = true,
        crossAxis: checkCrossAxis = true,
        fallbackPlacements: specifiedFallbackPlacements,
        fallbackStrategy = "bestFit",
        fallbackAxisSideDirection = "none",
        flipAlignment = true,
        ...detectOverflowOptions
      } = evaluate(options, state);
      if ((_middlewareData$arrow = middlewareData.arrow) != null && _middlewareData$arrow.alignmentOffset) {
        return {};
      }
      const side = getSide(placement);
      const initialSideAxis = getSideAxis(initialPlacement);
      const isBasePlacement = getSide(initialPlacement) === initialPlacement;
      const rtl = await (platform2.isRTL == null ? void 0 : platform2.isRTL(elements.floating));
      const fallbackPlacements = specifiedFallbackPlacements || (isBasePlacement || !flipAlignment ? [getOppositePlacement(initialPlacement)] : getExpandedPlacements(initialPlacement));
      const hasFallbackAxisSideDirection = fallbackAxisSideDirection !== "none";
      if (!specifiedFallbackPlacements && hasFallbackAxisSideDirection) {
        fallbackPlacements.push(...getOppositeAxisPlacements(initialPlacement, flipAlignment, fallbackAxisSideDirection, rtl));
      }
      const placements2 = [initialPlacement, ...fallbackPlacements];
      const overflow = await platform2.detectOverflow(state, detectOverflowOptions);
      const overflows = [];
      let overflowsData = ((_middlewareData$flip = middlewareData.flip) == null ? void 0 : _middlewareData$flip.overflows) || [];
      if (checkMainAxis) {
        overflows.push(overflow[side]);
      }
      if (checkCrossAxis) {
        const sides2 = getAlignmentSides(placement, rects, rtl);
        overflows.push(overflow[sides2[0]], overflow[sides2[1]]);
      }
      overflowsData = [...overflowsData, {
        placement,
        overflows
      }];
      if (!overflows.every((side2) => side2 <= 0)) {
        var _middlewareData$flip2, _overflowsData$filter;
        const nextIndex = (((_middlewareData$flip2 = middlewareData.flip) == null ? void 0 : _middlewareData$flip2.index) || 0) + 1;
        const nextPlacement = placements2[nextIndex];
        if (nextPlacement) {
          const ignoreCrossAxisOverflow = checkCrossAxis === "alignment" ? initialSideAxis !== getSideAxis(nextPlacement) : false;
          if (!ignoreCrossAxisOverflow || // We leave the current main axis only if every placement on that axis
          // overflows the main axis.
          overflowsData.every((d) => getSideAxis(d.placement) === initialSideAxis ? d.overflows[0] > 0 : true)) {
            return {
              data: {
                index: nextIndex,
                overflows: overflowsData
              },
              reset: {
                placement: nextPlacement
              }
            };
          }
        }
        let resetPlacement = (_overflowsData$filter = overflowsData.filter((d) => d.overflows[0] <= 0).sort((a, b) => a.overflows[1] - b.overflows[1])[0]) == null ? void 0 : _overflowsData$filter.placement;
        if (!resetPlacement) {
          switch (fallbackStrategy) {
            case "bestFit": {
              var _overflowsData$filter2;
              const placement2 = (_overflowsData$filter2 = overflowsData.filter((d) => {
                if (hasFallbackAxisSideDirection) {
                  const currentSideAxis = getSideAxis(d.placement);
                  return currentSideAxis === initialSideAxis || // Create a bias to the `y` side axis due to horizontal
                  // reading directions favoring greater width.
                  currentSideAxis === "y";
                }
                return true;
              }).map((d) => [d.placement, d.overflows.filter((overflow2) => overflow2 > 0).reduce((acc, overflow2) => acc + overflow2, 0)]).sort((a, b) => a[1] - b[1])[0]) == null ? void 0 : _overflowsData$filter2[0];
              if (placement2) {
                resetPlacement = placement2;
              }
              break;
            }
            case "initialPlacement":
              resetPlacement = initialPlacement;
              break;
          }
        }
        if (placement !== resetPlacement) {
          return {
            reset: {
              placement: resetPlacement
            }
          };
        }
      }
      return {};
    }
  };
};
var originSides = /* @__PURE__ */ new Set(["left", "top"]);
async function convertValueToCoords(state, options) {
  const {
    placement,
    platform: platform2,
    elements
  } = state;
  const rtl = await (platform2.isRTL == null ? void 0 : platform2.isRTL(elements.floating));
  const side = getSide(placement);
  const alignment = getAlignment(placement);
  const isVertical = getSideAxis(placement) === "y";
  const mainAxisMulti = originSides.has(side) ? -1 : 1;
  const crossAxisMulti = rtl && isVertical ? -1 : 1;
  const rawValue = evaluate(options, state);
  let {
    mainAxis,
    crossAxis,
    alignmentAxis
  } = typeof rawValue === "number" ? {
    mainAxis: rawValue,
    crossAxis: 0,
    alignmentAxis: null
  } : {
    mainAxis: rawValue.mainAxis || 0,
    crossAxis: rawValue.crossAxis || 0,
    alignmentAxis: rawValue.alignmentAxis
  };
  if (alignment && typeof alignmentAxis === "number") {
    crossAxis = alignment === "end" ? alignmentAxis * -1 : alignmentAxis;
  }
  return isVertical ? {
    x: crossAxis * crossAxisMulti,
    y: mainAxis * mainAxisMulti
  } : {
    x: mainAxis * mainAxisMulti,
    y: crossAxis * crossAxisMulti
  };
}
var offset = function(options) {
  if (options === void 0) {
    options = 0;
  }
  return {
    name: "offset",
    options,
    async fn(state) {
      var _middlewareData$offse, _middlewareData$arrow;
      const {
        x,
        y,
        placement,
        middlewareData
      } = state;
      const diffCoords = await convertValueToCoords(state, options);
      if (placement === ((_middlewareData$offse = middlewareData.offset) == null ? void 0 : _middlewareData$offse.placement) && (_middlewareData$arrow = middlewareData.arrow) != null && _middlewareData$arrow.alignmentOffset) {
        return {};
      }
      return {
        x: x + diffCoords.x,
        y: y + diffCoords.y,
        data: {
          ...diffCoords,
          placement
        }
      };
    }
  };
};
var shift = function(options) {
  if (options === void 0) {
    options = {};
  }
  return {
    name: "shift",
    options,
    async fn(state) {
      const {
        x,
        y,
        placement,
        platform: platform2
      } = state;
      const {
        mainAxis: checkMainAxis = true,
        crossAxis: checkCrossAxis = false,
        limiter = {
          fn: (_ref) => {
            let {
              x: x2,
              y: y2
            } = _ref;
            return {
              x: x2,
              y: y2
            };
          }
        },
        ...detectOverflowOptions
      } = evaluate(options, state);
      const coords = {
        x,
        y
      };
      const overflow = await platform2.detectOverflow(state, detectOverflowOptions);
      const crossAxis = getSideAxis(getSide(placement));
      const mainAxis = getOppositeAxis(crossAxis);
      let mainAxisCoord = coords[mainAxis];
      let crossAxisCoord = coords[crossAxis];
      if (checkMainAxis) {
        const minSide = mainAxis === "y" ? "top" : "left";
        const maxSide = mainAxis === "y" ? "bottom" : "right";
        const min2 = mainAxisCoord + overflow[minSide];
        const max2 = mainAxisCoord - overflow[maxSide];
        mainAxisCoord = clamp(min2, mainAxisCoord, max2);
      }
      if (checkCrossAxis) {
        const minSide = crossAxis === "y" ? "top" : "left";
        const maxSide = crossAxis === "y" ? "bottom" : "right";
        const min2 = crossAxisCoord + overflow[minSide];
        const max2 = crossAxisCoord - overflow[maxSide];
        crossAxisCoord = clamp(min2, crossAxisCoord, max2);
      }
      const limitedCoords = limiter.fn({
        ...state,
        [mainAxis]: mainAxisCoord,
        [crossAxis]: crossAxisCoord
      });
      return {
        ...limitedCoords,
        data: {
          x: limitedCoords.x - x,
          y: limitedCoords.y - y,
          enabled: {
            [mainAxis]: checkMainAxis,
            [crossAxis]: checkCrossAxis
          }
        }
      };
    }
  };
};
var size = function(options) {
  if (options === void 0) {
    options = {};
  }
  return {
    name: "size",
    options,
    async fn(state) {
      var _state$middlewareData, _state$middlewareData2;
      const {
        placement,
        rects,
        platform: platform2,
        elements
      } = state;
      const {
        apply = () => {
        },
        ...detectOverflowOptions
      } = evaluate(options, state);
      const overflow = await platform2.detectOverflow(state, detectOverflowOptions);
      const side = getSide(placement);
      const alignment = getAlignment(placement);
      const isYAxis = getSideAxis(placement) === "y";
      const {
        width,
        height
      } = rects.floating;
      let heightSide;
      let widthSide;
      if (side === "top" || side === "bottom") {
        heightSide = side;
        widthSide = alignment === (await (platform2.isRTL == null ? void 0 : platform2.isRTL(elements.floating)) ? "start" : "end") ? "left" : "right";
      } else {
        widthSide = side;
        heightSide = alignment === "end" ? "top" : "bottom";
      }
      const maximumClippingHeight = height - overflow.top - overflow.bottom;
      const maximumClippingWidth = width - overflow.left - overflow.right;
      const overflowAvailableHeight = min(height - overflow[heightSide], maximumClippingHeight);
      const overflowAvailableWidth = min(width - overflow[widthSide], maximumClippingWidth);
      const noShift = !state.middlewareData.shift;
      let availableHeight = overflowAvailableHeight;
      let availableWidth = overflowAvailableWidth;
      if ((_state$middlewareData = state.middlewareData.shift) != null && _state$middlewareData.enabled.x) {
        availableWidth = maximumClippingWidth;
      }
      if ((_state$middlewareData2 = state.middlewareData.shift) != null && _state$middlewareData2.enabled.y) {
        availableHeight = maximumClippingHeight;
      }
      if (noShift && !alignment) {
        const xMin = max(overflow.left, 0);
        const xMax = max(overflow.right, 0);
        const yMin = max(overflow.top, 0);
        const yMax = max(overflow.bottom, 0);
        if (isYAxis) {
          availableWidth = width - 2 * (xMin !== 0 || xMax !== 0 ? xMin + xMax : max(overflow.left, overflow.right));
        } else {
          availableHeight = height - 2 * (yMin !== 0 || yMax !== 0 ? yMin + yMax : max(overflow.top, overflow.bottom));
        }
      }
      await apply({
        ...state,
        availableWidth,
        availableHeight
      });
      const nextDimensions = await platform2.getDimensions(elements.floating);
      if (width !== nextDimensions.width || height !== nextDimensions.height) {
        return {
          reset: {
            rects: true
          }
        };
      }
      return {};
    }
  };
};

// node_modules/@floating-ui/utils/dist/floating-ui.utils.dom.mjs
function hasWindow() {
  return typeof window !== "undefined";
}
function getNodeName(node) {
  if (isNode(node)) {
    return (node.nodeName || "").toLowerCase();
  }
  return "#document";
}
function getWindow(node) {
  var _node$ownerDocument;
  return (node == null || (_node$ownerDocument = node.ownerDocument) == null ? void 0 : _node$ownerDocument.defaultView) || window;
}
function getDocumentElement(node) {
  var _ref;
  return (_ref = (isNode(node) ? node.ownerDocument : node.document) || window.document) == null ? void 0 : _ref.documentElement;
}
function isNode(value) {
  if (!hasWindow()) {
    return false;
  }
  return value instanceof Node || value instanceof getWindow(value).Node;
}
function isElement(value) {
  if (!hasWindow()) {
    return false;
  }
  return value instanceof Element || value instanceof getWindow(value).Element;
}
function isHTMLElement(value) {
  if (!hasWindow()) {
    return false;
  }
  return value instanceof HTMLElement || value instanceof getWindow(value).HTMLElement;
}
function isShadowRoot(value) {
  if (!hasWindow() || typeof ShadowRoot === "undefined") {
    return false;
  }
  return value instanceof ShadowRoot || value instanceof getWindow(value).ShadowRoot;
}
function isOverflowElement(element) {
  const {
    overflow,
    overflowX,
    overflowY,
    display
  } = getComputedStyle2(element);
  return /auto|scroll|overlay|hidden|clip/.test(overflow + overflowY + overflowX) && display !== "inline" && display !== "contents";
}
function isTableElement(element) {
  return /^(table|td|th)$/.test(getNodeName(element));
}
function isTopLayer(element) {
  try {
    if (element.matches(":popover-open")) {
      return true;
    }
  } catch (_e) {
  }
  try {
    return element.matches(":modal");
  } catch (_e) {
    return false;
  }
}
var willChangeRe = /transform|translate|scale|rotate|perspective|filter/;
var containRe = /paint|layout|strict|content/;
var isNotNone = (value) => !!value && value !== "none";
var isWebKitValue;
function isContainingBlock(elementOrCss) {
  const css = isElement(elementOrCss) ? getComputedStyle2(elementOrCss) : elementOrCss;
  return isNotNone(css.transform) || isNotNone(css.translate) || isNotNone(css.scale) || isNotNone(css.rotate) || isNotNone(css.perspective) || !isWebKit() && (isNotNone(css.backdropFilter) || isNotNone(css.filter)) || willChangeRe.test(css.willChange || "") || containRe.test(css.contain || "");
}
function getContainingBlock(element) {
  let currentNode = getParentNode(element);
  while (isHTMLElement(currentNode) && !isLastTraversableNode(currentNode)) {
    if (isContainingBlock(currentNode)) {
      return currentNode;
    } else if (isTopLayer(currentNode)) {
      return null;
    }
    currentNode = getParentNode(currentNode);
  }
  return null;
}
function isWebKit() {
  if (isWebKitValue == null) {
    isWebKitValue = typeof CSS !== "undefined" && CSS.supports && CSS.supports("-webkit-backdrop-filter", "none");
  }
  return isWebKitValue;
}
function isLastTraversableNode(node) {
  return /^(html|body|#document)$/.test(getNodeName(node));
}
function getComputedStyle2(element) {
  return getWindow(element).getComputedStyle(element);
}
function getNodeScroll(element) {
  if (isElement(element)) {
    return {
      scrollLeft: element.scrollLeft,
      scrollTop: element.scrollTop
    };
  }
  return {
    scrollLeft: element.scrollX,
    scrollTop: element.scrollY
  };
}
function getParentNode(node) {
  if (getNodeName(node) === "html") {
    return node;
  }
  const result = (
    // Step into the shadow DOM of the parent of a slotted node.
    node.assignedSlot || // DOM Element detected.
    node.parentNode || // ShadowRoot detected.
    isShadowRoot(node) && node.host || // Fallback.
    getDocumentElement(node)
  );
  return isShadowRoot(result) ? result.host : result;
}
function getNearestOverflowAncestor(node) {
  const parentNode = getParentNode(node);
  if (isLastTraversableNode(parentNode)) {
    return node.ownerDocument ? node.ownerDocument.body : node.body;
  }
  if (isHTMLElement(parentNode) && isOverflowElement(parentNode)) {
    return parentNode;
  }
  return getNearestOverflowAncestor(parentNode);
}
function getOverflowAncestors(node, list, traverseIframes) {
  var _node$ownerDocument2;
  if (list === void 0) {
    list = [];
  }
  if (traverseIframes === void 0) {
    traverseIframes = true;
  }
  const scrollableAncestor = getNearestOverflowAncestor(node);
  const isBody = scrollableAncestor === ((_node$ownerDocument2 = node.ownerDocument) == null ? void 0 : _node$ownerDocument2.body);
  const win = getWindow(scrollableAncestor);
  if (isBody) {
    const frameElement = getFrameElement(win);
    return list.concat(win, win.visualViewport || [], isOverflowElement(scrollableAncestor) ? scrollableAncestor : [], frameElement && traverseIframes ? getOverflowAncestors(frameElement) : []);
  } else {
    return list.concat(scrollableAncestor, getOverflowAncestors(scrollableAncestor, [], traverseIframes));
  }
}
function getFrameElement(win) {
  return win.parent && Object.getPrototypeOf(win.parent) ? win.frameElement : null;
}

// node_modules/@floating-ui/dom/dist/floating-ui.dom.mjs
function getCssDimensions(element) {
  const css = getComputedStyle2(element);
  let width = parseFloat(css.width) || 0;
  let height = parseFloat(css.height) || 0;
  const hasOffset = isHTMLElement(element);
  const offsetWidth = hasOffset ? element.offsetWidth : width;
  const offsetHeight = hasOffset ? element.offsetHeight : height;
  const shouldFallback = round(width) !== offsetWidth || round(height) !== offsetHeight;
  if (shouldFallback) {
    width = offsetWidth;
    height = offsetHeight;
  }
  return {
    width,
    height,
    $: shouldFallback
  };
}
function unwrapElement(element) {
  return !isElement(element) ? element.contextElement : element;
}
function getScale(element) {
  const domElement = unwrapElement(element);
  if (!isHTMLElement(domElement)) {
    return createCoords(1);
  }
  const rect = domElement.getBoundingClientRect();
  const {
    width,
    height,
    $
  } = getCssDimensions(domElement);
  let x = ($ ? round(rect.width) : rect.width) / width;
  let y = ($ ? round(rect.height) : rect.height) / height;
  if (!x || !Number.isFinite(x)) {
    x = 1;
  }
  if (!y || !Number.isFinite(y)) {
    y = 1;
  }
  return {
    x,
    y
  };
}
var noOffsets = /* @__PURE__ */ createCoords(0);
function getVisualOffsets(element) {
  const win = getWindow(element);
  if (!isWebKit() || !win.visualViewport) {
    return noOffsets;
  }
  return {
    x: win.visualViewport.offsetLeft,
    y: win.visualViewport.offsetTop
  };
}
function shouldAddVisualOffsets(element, isFixed, floatingOffsetParent) {
  if (isFixed === void 0) {
    isFixed = false;
  }
  if (!floatingOffsetParent || isFixed && floatingOffsetParent !== getWindow(element)) {
    return false;
  }
  return isFixed;
}
function getBoundingClientRect(element, includeScale, isFixedStrategy, offsetParent) {
  if (includeScale === void 0) {
    includeScale = false;
  }
  if (isFixedStrategy === void 0) {
    isFixedStrategy = false;
  }
  const clientRect = element.getBoundingClientRect();
  const domElement = unwrapElement(element);
  let scale = createCoords(1);
  if (includeScale) {
    if (offsetParent) {
      if (isElement(offsetParent)) {
        scale = getScale(offsetParent);
      }
    } else {
      scale = getScale(element);
    }
  }
  const visualOffsets = shouldAddVisualOffsets(domElement, isFixedStrategy, offsetParent) ? getVisualOffsets(domElement) : createCoords(0);
  let x = (clientRect.left + visualOffsets.x) / scale.x;
  let y = (clientRect.top + visualOffsets.y) / scale.y;
  let width = clientRect.width / scale.x;
  let height = clientRect.height / scale.y;
  if (domElement) {
    const win = getWindow(domElement);
    const offsetWin = offsetParent && isElement(offsetParent) ? getWindow(offsetParent) : offsetParent;
    let currentWin = win;
    let currentIFrame = getFrameElement(currentWin);
    while (currentIFrame && offsetParent && offsetWin !== currentWin) {
      const iframeScale = getScale(currentIFrame);
      const iframeRect = currentIFrame.getBoundingClientRect();
      const css = getComputedStyle2(currentIFrame);
      const left = iframeRect.left + (currentIFrame.clientLeft + parseFloat(css.paddingLeft)) * iframeScale.x;
      const top = iframeRect.top + (currentIFrame.clientTop + parseFloat(css.paddingTop)) * iframeScale.y;
      x *= iframeScale.x;
      y *= iframeScale.y;
      width *= iframeScale.x;
      height *= iframeScale.y;
      x += left;
      y += top;
      currentWin = getWindow(currentIFrame);
      currentIFrame = getFrameElement(currentWin);
    }
  }
  return rectToClientRect({
    width,
    height,
    x,
    y
  });
}
function getWindowScrollBarX(element, rect) {
  const leftScroll = getNodeScroll(element).scrollLeft;
  if (!rect) {
    return getBoundingClientRect(getDocumentElement(element)).left + leftScroll;
  }
  return rect.left + leftScroll;
}
function getHTMLOffset(documentElement, scroll) {
  const htmlRect = documentElement.getBoundingClientRect();
  const x = htmlRect.left + scroll.scrollLeft - getWindowScrollBarX(documentElement, htmlRect);
  const y = htmlRect.top + scroll.scrollTop;
  return {
    x,
    y
  };
}
function convertOffsetParentRelativeRectToViewportRelativeRect(_ref) {
  let {
    elements,
    rect,
    offsetParent,
    strategy
  } = _ref;
  const isFixed = strategy === "fixed";
  const documentElement = getDocumentElement(offsetParent);
  const topLayer = elements ? isTopLayer(elements.floating) : false;
  if (offsetParent === documentElement || topLayer && isFixed) {
    return rect;
  }
  let scroll = {
    scrollLeft: 0,
    scrollTop: 0
  };
  let scale = createCoords(1);
  const offsets = createCoords(0);
  const isOffsetParentAnElement = isHTMLElement(offsetParent);
  if (isOffsetParentAnElement || !isOffsetParentAnElement && !isFixed) {
    if (getNodeName(offsetParent) !== "body" || isOverflowElement(documentElement)) {
      scroll = getNodeScroll(offsetParent);
    }
    if (isOffsetParentAnElement) {
      const offsetRect = getBoundingClientRect(offsetParent);
      scale = getScale(offsetParent);
      offsets.x = offsetRect.x + offsetParent.clientLeft;
      offsets.y = offsetRect.y + offsetParent.clientTop;
    }
  }
  const htmlOffset = documentElement && !isOffsetParentAnElement && !isFixed ? getHTMLOffset(documentElement, scroll) : createCoords(0);
  return {
    width: rect.width * scale.x,
    height: rect.height * scale.y,
    x: rect.x * scale.x - scroll.scrollLeft * scale.x + offsets.x + htmlOffset.x,
    y: rect.y * scale.y - scroll.scrollTop * scale.y + offsets.y + htmlOffset.y
  };
}
function getClientRects(element) {
  return Array.from(element.getClientRects());
}
function getDocumentRect(element) {
  const html = getDocumentElement(element);
  const scroll = getNodeScroll(element);
  const body = element.ownerDocument.body;
  const width = max(html.scrollWidth, html.clientWidth, body.scrollWidth, body.clientWidth);
  const height = max(html.scrollHeight, html.clientHeight, body.scrollHeight, body.clientHeight);
  let x = -scroll.scrollLeft + getWindowScrollBarX(element);
  const y = -scroll.scrollTop;
  if (getComputedStyle2(body).direction === "rtl") {
    x += max(html.clientWidth, body.clientWidth) - width;
  }
  return {
    width,
    height,
    x,
    y
  };
}
var SCROLLBAR_MAX = 25;
function getViewportRect(element, strategy) {
  const win = getWindow(element);
  const html = getDocumentElement(element);
  const visualViewport = win.visualViewport;
  let width = html.clientWidth;
  let height = html.clientHeight;
  let x = 0;
  let y = 0;
  if (visualViewport) {
    width = visualViewport.width;
    height = visualViewport.height;
    const visualViewportBased = isWebKit();
    if (!visualViewportBased || visualViewportBased && strategy === "fixed") {
      x = visualViewport.offsetLeft;
      y = visualViewport.offsetTop;
    }
  }
  const windowScrollbarX = getWindowScrollBarX(html);
  if (windowScrollbarX <= 0) {
    const doc = html.ownerDocument;
    const body = doc.body;
    const bodyStyles = getComputedStyle(body);
    const bodyMarginInline = doc.compatMode === "CSS1Compat" ? parseFloat(bodyStyles.marginLeft) + parseFloat(bodyStyles.marginRight) || 0 : 0;
    const clippingStableScrollbarWidth = Math.abs(html.clientWidth - body.clientWidth - bodyMarginInline);
    if (clippingStableScrollbarWidth <= SCROLLBAR_MAX) {
      width -= clippingStableScrollbarWidth;
    }
  } else if (windowScrollbarX <= SCROLLBAR_MAX) {
    width += windowScrollbarX;
  }
  return {
    width,
    height,
    x,
    y
  };
}
function getInnerBoundingClientRect(element, strategy) {
  const clientRect = getBoundingClientRect(element, true, strategy === "fixed");
  const top = clientRect.top + element.clientTop;
  const left = clientRect.left + element.clientLeft;
  const scale = isHTMLElement(element) ? getScale(element) : createCoords(1);
  const width = element.clientWidth * scale.x;
  const height = element.clientHeight * scale.y;
  const x = left * scale.x;
  const y = top * scale.y;
  return {
    width,
    height,
    x,
    y
  };
}
function getClientRectFromClippingAncestor(element, clippingAncestor, strategy) {
  let rect;
  if (clippingAncestor === "viewport") {
    rect = getViewportRect(element, strategy);
  } else if (clippingAncestor === "document") {
    rect = getDocumentRect(getDocumentElement(element));
  } else if (isElement(clippingAncestor)) {
    rect = getInnerBoundingClientRect(clippingAncestor, strategy);
  } else {
    const visualOffsets = getVisualOffsets(element);
    rect = {
      x: clippingAncestor.x - visualOffsets.x,
      y: clippingAncestor.y - visualOffsets.y,
      width: clippingAncestor.width,
      height: clippingAncestor.height
    };
  }
  return rectToClientRect(rect);
}
function hasFixedPositionAncestor(element, stopNode) {
  const parentNode = getParentNode(element);
  if (parentNode === stopNode || !isElement(parentNode) || isLastTraversableNode(parentNode)) {
    return false;
  }
  return getComputedStyle2(parentNode).position === "fixed" || hasFixedPositionAncestor(parentNode, stopNode);
}
function getClippingElementAncestors(element, cache) {
  const cachedResult = cache.get(element);
  if (cachedResult) {
    return cachedResult;
  }
  let result = getOverflowAncestors(element, [], false).filter((el) => isElement(el) && getNodeName(el) !== "body");
  let currentContainingBlockComputedStyle = null;
  const elementIsFixed = getComputedStyle2(element).position === "fixed";
  let currentNode = elementIsFixed ? getParentNode(element) : element;
  while (isElement(currentNode) && !isLastTraversableNode(currentNode)) {
    const computedStyle = getComputedStyle2(currentNode);
    const currentNodeIsContaining = isContainingBlock(currentNode);
    if (!currentNodeIsContaining && computedStyle.position === "fixed") {
      currentContainingBlockComputedStyle = null;
    }
    const shouldDropCurrentNode = elementIsFixed ? !currentNodeIsContaining && !currentContainingBlockComputedStyle : !currentNodeIsContaining && computedStyle.position === "static" && !!currentContainingBlockComputedStyle && (currentContainingBlockComputedStyle.position === "absolute" || currentContainingBlockComputedStyle.position === "fixed") || isOverflowElement(currentNode) && !currentNodeIsContaining && hasFixedPositionAncestor(element, currentNode);
    if (shouldDropCurrentNode) {
      result = result.filter((ancestor) => ancestor !== currentNode);
    } else {
      currentContainingBlockComputedStyle = computedStyle;
    }
    currentNode = getParentNode(currentNode);
  }
  cache.set(element, result);
  return result;
}
function getClippingRect(_ref) {
  let {
    element,
    boundary,
    rootBoundary,
    strategy
  } = _ref;
  const elementClippingAncestors = boundary === "clippingAncestors" ? isTopLayer(element) ? [] : getClippingElementAncestors(element, this._c) : [].concat(boundary);
  const clippingAncestors = [...elementClippingAncestors, rootBoundary];
  const firstRect = getClientRectFromClippingAncestor(element, clippingAncestors[0], strategy);
  let top = firstRect.top;
  let right = firstRect.right;
  let bottom = firstRect.bottom;
  let left = firstRect.left;
  for (let i = 1; i < clippingAncestors.length; i++) {
    const rect = getClientRectFromClippingAncestor(element, clippingAncestors[i], strategy);
    top = max(rect.top, top);
    right = min(rect.right, right);
    bottom = min(rect.bottom, bottom);
    left = max(rect.left, left);
  }
  return {
    width: right - left,
    height: bottom - top,
    x: left,
    y: top
  };
}
function getDimensions(element) {
  const {
    width,
    height
  } = getCssDimensions(element);
  return {
    width,
    height
  };
}
function getRectRelativeToOffsetParent(element, offsetParent, strategy) {
  const isOffsetParentAnElement = isHTMLElement(offsetParent);
  const documentElement = getDocumentElement(offsetParent);
  const isFixed = strategy === "fixed";
  const rect = getBoundingClientRect(element, true, isFixed, offsetParent);
  let scroll = {
    scrollLeft: 0,
    scrollTop: 0
  };
  const offsets = createCoords(0);
  function setLeftRTLScrollbarOffset() {
    offsets.x = getWindowScrollBarX(documentElement);
  }
  if (isOffsetParentAnElement || !isOffsetParentAnElement && !isFixed) {
    if (getNodeName(offsetParent) !== "body" || isOverflowElement(documentElement)) {
      scroll = getNodeScroll(offsetParent);
    }
    if (isOffsetParentAnElement) {
      const offsetRect = getBoundingClientRect(offsetParent, true, isFixed, offsetParent);
      offsets.x = offsetRect.x + offsetParent.clientLeft;
      offsets.y = offsetRect.y + offsetParent.clientTop;
    } else if (documentElement) {
      setLeftRTLScrollbarOffset();
    }
  }
  if (isFixed && !isOffsetParentAnElement && documentElement) {
    setLeftRTLScrollbarOffset();
  }
  const htmlOffset = documentElement && !isOffsetParentAnElement && !isFixed ? getHTMLOffset(documentElement, scroll) : createCoords(0);
  const x = rect.left + scroll.scrollLeft - offsets.x - htmlOffset.x;
  const y = rect.top + scroll.scrollTop - offsets.y - htmlOffset.y;
  return {
    x,
    y,
    width: rect.width,
    height: rect.height
  };
}
function isStaticPositioned(element) {
  return getComputedStyle2(element).position === "static";
}
function getTrueOffsetParent(element, polyfill) {
  if (!isHTMLElement(element) || getComputedStyle2(element).position === "fixed") {
    return null;
  }
  if (polyfill) {
    return polyfill(element);
  }
  let rawOffsetParent = element.offsetParent;
  if (getDocumentElement(element) === rawOffsetParent) {
    rawOffsetParent = rawOffsetParent.ownerDocument.body;
  }
  return rawOffsetParent;
}
function getOffsetParent(element, polyfill) {
  const win = getWindow(element);
  if (isTopLayer(element)) {
    return win;
  }
  if (!isHTMLElement(element)) {
    let svgOffsetParent = getParentNode(element);
    while (svgOffsetParent && !isLastTraversableNode(svgOffsetParent)) {
      if (isElement(svgOffsetParent) && !isStaticPositioned(svgOffsetParent)) {
        return svgOffsetParent;
      }
      svgOffsetParent = getParentNode(svgOffsetParent);
    }
    return win;
  }
  let offsetParent = getTrueOffsetParent(element, polyfill);
  while (offsetParent && isTableElement(offsetParent) && isStaticPositioned(offsetParent)) {
    offsetParent = getTrueOffsetParent(offsetParent, polyfill);
  }
  if (offsetParent && isLastTraversableNode(offsetParent) && isStaticPositioned(offsetParent) && !isContainingBlock(offsetParent)) {
    return win;
  }
  return offsetParent || getContainingBlock(element) || win;
}
var getElementRects = async function(data) {
  const getOffsetParentFn = this.getOffsetParent || getOffsetParent;
  const getDimensionsFn = this.getDimensions;
  const floatingDimensions = await getDimensionsFn(data.floating);
  return {
    reference: getRectRelativeToOffsetParent(data.reference, await getOffsetParentFn(data.floating), data.strategy),
    floating: {
      x: 0,
      y: 0,
      width: floatingDimensions.width,
      height: floatingDimensions.height
    }
  };
};
function isRTL(element) {
  return getComputedStyle2(element).direction === "rtl";
}
var platform = {
  convertOffsetParentRelativeRectToViewportRelativeRect,
  getDocumentElement,
  getClippingRect,
  getOffsetParent,
  getElementRects,
  getClientRects,
  getDimensions,
  getScale,
  isElement,
  isRTL
};
var offset2 = offset;
var shift2 = shift;
var flip2 = flip;
var size2 = size;
var computePosition2 = (reference, floating, options) => {
  const cache = /* @__PURE__ */ new Map();
  const mergedOptions = {
    platform,
    ...options
  };
  const platformWithCache = {
    ...mergedOptions.platform,
    _c: cache
  };
  return computePosition(reference, floating, {
    ...mergedOptions,
    platform: platformWithCache
  });
};

// src/context-menu.ts
function dismissAllMenus() {
  const menus = document.querySelectorAll("[data-sm-menu]");
  Array.from(menus).forEach((el) => {
    const smEl = el;
    clearTimeouts(smEl);
    const markDismissed = smEl._smDismissed;
    if (markDismissed)
      markDismissed();
    const cleanup = smEl._smCleanup;
    if (cleanup)
      cleanup();
    smEl.remove();
  });
}
function clearTimeouts(el) {
  const groups = el.querySelectorAll("[data-sm-timeouts]");
  Array.from(groups).forEach((g) => {
    const ids = g.dataset.smTimeouts;
    if (ids) {
      ids.split(",").forEach((id) => {
        const n = parseInt(id, 10);
        if (!isNaN(n))
          clearTimeout(n);
      });
    }
  });
}
function showContextMenu(ev, profile, app) {
  const bodyZoom = parseFloat(document.body.style.zoom) || 1;
  const x = ev.clientX / bodyZoom;
  const y = ev.clientY / bodyZoom;
  const menuEl = buildMenu(profile, app);
  menuEl.setAttribute("data-sm-menu", "");
  document.body.appendChild(menuEl);
  let dismissed = false;
  menuEl._smDismissed = () => dismissed = true;
  const virtualEl = {
    getBoundingClientRect: () => DOMRect.fromRect({ x, y, width: 0, height: 0 })
  };
  computePosition2(virtualEl, menuEl, {
    placement: "bottom-start",
    middleware: [
      offset2(4),
      flip2({ padding: 10 }),
      shift2({ padding: 10 }),
      size2({
        apply({ availableHeight, elements }) {
          elements.floating.style.maxHeight = `${Math.max(Math.min(availableHeight - 16, 600), 100)}px`;
          elements.floating.style.overflowY = "auto";
        },
        padding: 8
      })
    ]
  }).then(({ x: fx, y: fy }) => {
    if (dismissed)
      return;
    menuEl.style.left = `${Math.floor(fx)}px`;
    menuEl.style.top = `${Math.floor(fy)}px`;
  });
  const cleanup = registerDismissHandlers(menuEl);
  menuEl._smCleanup = cleanup;
}
function buildMenu(profile, app) {
  const menu = document.createElement("div");
  menu.className = "sm-menu";
  if (profile.mainMenuCommands.length === 0 && Object.keys(profile.submenus).length === 0) {
    const empty = menu.createDiv({ cls: "sm-menu-empty", text: "No commands configured" });
    empty.style.cssText = "padding: 12px 16px; color: var(--text-muted); font-size: 12px; text-align: center;";
    return menu;
  }
  for (const cmd of profile.mainMenuCommands) {
    if (!cmd.commandId)
      continue;
    menu.appendChild(createItem(cmd, app));
  }
  if (profile.mainMenuCommands.length > 0 && Object.keys(profile.submenus).length > 0) {
    menu.appendChild(createSeparator());
  }
  for (const [groupName, entries] of Object.entries(profile.submenus)) {
    const valid = entries.filter((e) => e.commandId);
    if (valid.length === 0)
      continue;
    menu.appendChild(createGroup(groupName, valid, app));
  }
  return menu;
}
function createItem(entry, app) {
  const item = document.createElement("div");
  item.className = "sm-menu-item";
  if (entry.icon) {
    const iconEl = item.createSpan({ cls: "sm-menu-item-icon" });
    try {
      (0, import_obsidian3.setIcon)(iconEl, entry.icon);
    } catch (e) {
    }
  }
  item.createSpan({ cls: "sm-menu-item-label", text: entry.label });
  item.addEventListener("click", (e) => {
    e.stopPropagation();
    dismissAllMenus();
    app.commands.executeCommandById(entry.commandId);
  });
  return item;
}
function createGroup(name, entries, app) {
  const group = document.createElement("div");
  group.className = "sm-menu-group";
  const trigger = document.createElement("div");
  trigger.className = "sm-menu-item sm-group-trigger";
  trigger.createSpan({ cls: "sm-menu-item-label", text: name });
  const arrow2 = trigger.createSpan({ cls: "sm-group-arrow" });
  (0, import_obsidian3.setIcon)(arrow2, "chevron-right");
  const submenu = document.createElement("div");
  submenu.className = "sm-submenu";
  for (const entry of entries) {
    submenu.appendChild(createItem(entry, app));
  }
  group.appendChild(trigger);
  group.appendChild(submenu);
  let hideTimeout = null;
  let showTimeout = null;
  const saveTimeouts = () => {
    const ids = [];
    if (showTimeout !== null)
      ids.push(showTimeout);
    if (hideTimeout !== null)
      ids.push(hideTimeout);
    group.dataset.smTimeouts = ids.join(",");
  };
  const show = () => {
    if (hideTimeout !== null)
      clearTimeout(hideTimeout);
    if (showTimeout !== null)
      clearTimeout(showTimeout);
    showTimeout = window.setTimeout(() => {
      submenu.classList.add("sm-submenu-visible");
      showTimeout = null;
      saveTimeouts();
    }, 150);
    saveTimeouts();
  };
  const hide2 = () => {
    if (showTimeout !== null)
      clearTimeout(showTimeout);
    if (hideTimeout !== null)
      clearTimeout(hideTimeout);
    hideTimeout = window.setTimeout(() => {
      submenu.classList.remove("sm-submenu-visible");
      hideTimeout = null;
      saveTimeouts();
    }, 200);
    saveTimeouts();
  };
  trigger.addEventListener("mouseenter", show);
  trigger.addEventListener("mouseleave", (e) => {
    const related = e.relatedTarget;
    if (!related || !submenu.contains(related))
      hide2();
  });
  submenu.addEventListener("mouseenter", () => {
    if (hideTimeout !== null)
      clearTimeout(hideTimeout);
    hideTimeout = null;
    submenu.classList.add("sm-submenu-visible");
    saveTimeouts();
  });
  submenu.addEventListener("mouseleave", (e) => {
    const related = e.relatedTarget;
    if (!related || !group.contains(related))
      hide2();
  });
  return group;
}
function createSeparator() {
  const sep = document.createElement("div");
  sep.className = "sm-menu-separator";
  return sep;
}
function registerDismissHandlers(menuEl) {
  const onKeyDown = (e) => {
    if (e.key === "Escape")
      dismissAllMenus();
  };
  const onClick = (e) => {
    if (!menuEl.contains(e.target))
      dismissAllMenus();
  };
  document.addEventListener("keydown", onKeyDown, true);
  document.addEventListener("click", onClick, true);
  return () => {
    document.removeEventListener("keydown", onKeyDown, true);
    document.removeEventListener("click", onClick, true);
  };
}

// src/main.ts
var ScriptMenusPlugin = class extends import_obsidian4.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new ScriptMenusSettingTab(this.app, this));
    this.registerDomEvent(document, "contextmenu", (ev) => {
      const view = this.app.workspace.getActiveViewOfType(import_obsidian4.MarkdownView);
      if (!view)
        return;
      if (view.getMode() !== "source")
        return;
      if (!view.contentEl.contains(ev.target))
        return;
      for (const profile of this.settings.profiles) {
        if (ev.altKey === profile.modifiers.alt && ev.ctrlKey === profile.modifiers.ctrl && ev.shiftKey === profile.modifiers.shift && ev.metaKey === profile.modifiers.meta) {
          ev.preventDefault();
          ev.stopPropagation();
          showContextMenu(ev, profile, this.app);
          return;
        }
      }
    });
  }
  onunload() {
    dismissAllMenus();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
