import https from "https";
import fs from "fs";
import path from "path";

const URL = "https://unpkg.com/lucide-static@0.344.0/tags.json";
const OUT = path.resolve(import.meta.dirname, "../src/generated/icon-list.ts");

https.get(URL, (res) => {
  let data = "";
  res.on("data", (chunk) => (data += chunk));
  res.on("end", () => {
    const tags = JSON.parse(data);
    const names = Object.keys(tags).sort().map((n) => `  "${n}"`).join(",\n");
    fs.mkdirSync(path.dirname(OUT), { recursive: true });
    fs.writeFileSync(OUT, `// Auto-generated by scripts/fetch-icons.mjs\nexport const ICON_LIST: string[] = [\n${names},\n];\n`, "utf-8");
    console.log(`Generated icon-list.ts with ${Object.keys(tags).length} icons`);
  });
}).on("error", (err) => {
  console.error("Failed to fetch icon list:", err.message);
  process.exit(1);
});
